In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import molsysmt as msm
import numpy as np

# Translate

In [3]:
molecular_system = msm.demo['Met-enkephalin']['vacuum.msmpk']
molecular_system = msm.convert(molecular_system)

In [4]:
msm.info(molecular_system)

In [5]:
msm.get(molecular_system, coordinates=True)

array([[[ 3.32577000e-01,  1.54790900e-01, -1.60000000e-07],
        [ 3.90940700e-01,  7.23611000e-02, -2.70000000e-07],
        [ 3.97004800e-01,  2.84579500e-01, -1.00000000e-08],
        ...,
        [ 1.81611387e+00,  1.49265091e+00,  2.28656910e-01],
        [ 1.78326004e+00,  1.04129617e+00, -5.60000000e-07],
        [ 1.83558834e+00,  9.30092970e-01, -1.51000000e-06]]]) <Unit('nanometer')>

In [6]:
n_atoms = msm.get(molecular_system, n_atoms=True)
shifts = np.ones([n_atoms,3], dtype=float)*msm.puw.unit('nm')

In [7]:
molecular_system = msm.structure.translate(molecular_system, translation=shifts)

In [8]:
coordinates = msm.get(molecular_system, coordinates=True)
coordinates

array([[[1.332577  , 1.1547909 , 0.99999984],
        [1.3909407 , 1.0723611 , 0.99999973],
        [1.3970048 , 1.2845795 , 0.99999999],
        ...,
        [2.81611387, 2.49265091, 1.22865691],
        [2.78326004, 2.04129617, 0.99999944],
        [2.83558834, 1.93009297, 0.99999849]]]) <Unit('nanometer')>

In [9]:
shifts = np.array([-1.0, -1.0, -1.0], dtype=float)*msm.puw.unit('nm')
molecular_system = msm.structure.translate(molecular_system, translation=shifts,
                                           selection=[0,1,2], in_place=False)

In [10]:
msm.get(molecular_system, coordinates=True)

array([[[ 3.32577000e-01,  1.54790900e-01, -1.60000000e-07],
        [ 3.90940700e-01,  7.23611000e-02, -2.70000000e-07],
        [ 3.97004800e-01,  2.84579500e-01, -1.00000001e-08],
        ...,
        [ 2.81611387e+00,  2.49265091e+00,  1.22865691e+00],
        [ 2.78326004e+00,  2.04129617e+00,  9.99999440e-01],
        [ 2.83558834e+00,  1.93009297e+00,  9.99998490e-01]]]) <Unit('nanometer')>