In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import molsysmt as msm

In [3]:
import numpy as np
import pyunitwizard as puw

In [4]:
molsys = msm.convert(msm.demo['Met-enkephalin']['vacuum.msmpk'], to_form='molsysmt.MolSys')

In [5]:
phi_chains = msm.topology.get_dihedral_quartets(molsys, phi=True)

In [6]:
msm.structure.get_dihedral_angles(molsys, quartets=phi_chains[2])

array([[-179.99976915]]) <Unit('degree')>

In [7]:
molsys_1 = msm.structure.set_dihedral_angles(molsys, quartets=phi_chains[2], angles='45.0 degrees', pbc=False)

[[[ 3.32577000e-01  1.54790900e-01 -1.60000000e-07]
  [ 3.90940700e-01  7.23611000e-02 -2.70000000e-07]
  [ 3.97004800e-01  2.84579500e-01 -1.00000000e-08]
  [ 3.67166300e-01  3.40012900e-01 -8.89820000e-02]
  [ 3.57696500e-01  3.65383800e-01  1.23214300e-01]
  [ 2.49699500e-01  3.80107500e-01  1.24137900e-01]
  [ 3.87748400e-01  3.11579500e-01  2.13119700e-01]
  [ 4.26732800e-01  4.99626700e-01  1.19494600e-01]
  [ 4.05992700e-01  5.91891100e-01  2.22728000e-01]
  [ 3.40010800e-01  5.66821800e-01  3.05787700e-01]
  [ 4.69999800e-01  7.16354700e-01  2.19279100e-01]
  [ 4.53852200e-01  7.88189100e-01  2.99653800e-01]
  [ 5.54747100e-01  7.48554200e-01  1.12597000e-01]
  [ 6.16925500e-01  8.69461700e-01  1.09246800e-01]
  [ 5.95632700e-01  9.24698400e-01  1.84821400e-01]
  [ 5.75487500e-01  6.56290000e-01  9.36350000e-03]
  [ 6.41469400e-01  6.81359500e-01 -7.36962000e-02]
  [ 5.11480600e-01  5.31826300e-01  1.28119000e-02]
  [ 5.27628600e-01  4.59992000e-01 -6.75627000e-02]
  [ 5.485541

In [8]:
msm.structure.get_dihedral_angles(molsys_1, quartets=phi_chains[2])

array([[-179.99976915]]) <Unit('degree')>