In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import molsysmt as msm

In [3]:
pdbs_to_be_tested = ["1BG3", "2PGI", "4PFK", "4ALD", "3YPI", "3GPD",
                    "13PK", "1BQ3", "7ENL", "1A3W"]

In [17]:
molsys = msm.convert('1A6M')

/home/diego/projects@dprada/MolSysMT/molsysmt/item/mmtf_MMTFDecoder/to_molsysmt_Topology.py:33: UserWarning: The structure in the PDB has biological assemblies. There are geometrical transformations proposed in the structure. See the following issue in the source code repository: https://github.com/uibcdf/MolSysMT/issues/33
  warnings.warn(warning_message)


In [16]:
msm.view(molsys)

/home/diego/Myopt/miniconda3/envs/MolSysMT@dprada_3.9/lib/python3.9/site-packages/pint_pandas/pint_array.py:648: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  return np.array(qtys, dtype="object", copy=copy)


NGLWidget()

In [18]:
aa = msm.select(molsys, element='atom', selection='occupancy<1.0')

/home/diego/Myopt/miniconda3/envs/MolSysMT@dprada_3.9/lib/python3.9/site-packages/pint_pandas/pint_array.py:648: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  return np.array(qtys, dtype="object", copy=copy)


In [6]:
if len(aa):
    print('si')

si


In [7]:
len(aa)

30

In [8]:
aa

array([2408, 2410, 2411, 2412, 2413, 2414, 2415, 2416, 2417, 2418, 2419,
       2420, 2421, 2422, 2423, 2424, 2425, 2426, 2427, 2428, 2429, 2430,
       2431, 2432, 2433, 2434, 2435, 2436, 2496, 2516])

In [14]:
msm.get(molsys, element='atom', occupancy=True)

array([1., 1., 1., ..., 1., 1., 1.])

In [10]:
msm.get(molsys, element='atom', selection=aa, occupancy=True)

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5])

In [11]:
msm.info(molsys, element='atom', selection=aa)