In [3]:
import molsysmt as msm
import numpy as np

In [4]:
molsys = msm.convert(msm.systems['two LJ particles']['traj_two_lj_particles.trjpk'], to_form='molsysmt.StructuresDict')
molsys_wrapped = msm.pbc.wrap_to_pbc(molsys)
molsys_unwrapped = msm.pbc.unwrap(molsys_wrapped)
box_length = msm.get(molsys_wrapped, element='system', box_lengths=True)[0,0]
check_limits_wrapped = ( box_length >= (np.max(molsys_wrapped['coordinates']) - np.min(molsys_wrapped['coordinates'])))
check_limits = ( box_length <= (np.max(molsys['coordinates']) - np.min(molsys['coordinates'])))
check_limits_unwrapped = ( box_length <= (np.max(molsys_unwrapped['coordinates']) - np.min(molsys['coordinates'])))
check = np.allclose(molsys_unwrapped['coordinates'][:,:,:], molsys['coordinates'][:,:,:])
assert check_limits
assert check_limits_unwrapped
assert check_limits_wrapped
assert check

/tmp/ipykernel_348258/1404998543.py:2: NotDigestedArgumentWarning: The periodicity_from from molsysmt.pbc.wrap_to_pbc.wrap_to_pbc argument was not digested.Check  for more information. If you still need help, open a new issue in https://github.com/uibcdf/MolSysMT/issues.
  molsys_wrapped = msm.pbc.wrap_to_pbc(molsys)


AssertionError: 

In [6]:
molsys['coordinates']

<Quantity([[[-2.9659176e-01 -6.9334745e-02 -3.0214071e-02]
  [ 9.7699082e-01  7.2899960e-02 -1.8030643e-02]]

 [[-7.5284719e-01 -1.8362737e-01 -2.0594621e-01]
  [ 8.3807111e-01  4.5254128e-03 -1.0873175e-01]]

 [[-8.9586782e-01 -1.1072683e-01 -5.1274061e-01]
  [ 7.8480154e-01 -1.6792607e-01 -1.4707398e-01]]

 ...

 [[-7.6136422e-01  1.1239279e+02  5.4138569e+01]
  [ 2.7399563e+01 -2.0351631e+01  1.3224771e+01]]

 [[-6.1515045e-01  1.1247175e+02  5.4431652e+01]
  [ 2.7676020e+01 -2.0524330e+01  1.3016828e+01]]

 [[-3.6927271e-01  1.1234875e+02  5.4812477e+01]
  [ 2.7741772e+01 -2.0716305e+01  1.2859294e+01]]], 'nanometer')>

In [7]:
molsys_unwrapped['coordinates']

<Quantity([[[ 2.70340824e+00  2.93066525e+00  2.96978593e+00]
  [ 9.76990819e-01  7.28999600e-02  2.98196936e+00]]

 [[ 2.24715281e+00  2.81637263e+00  2.79405379e+00]
  [ 8.38071108e-01  4.52541281e-03  2.89126825e+00]]

 [[ 2.10413218e+00  2.88927317e+00  2.48725939e+00]
  [ 7.84801543e-01 -1.67926073e-01  2.85292602e+00]]

 ...

 [[ 2.23863578e+00  1.15392792e+02  5.71385689e+01]
  [ 2.73995628e+01 -2.03516312e+01  1.62247705e+01]]

 [[ 2.38484955e+00  1.15471748e+02  5.74316521e+01]
  [ 2.76760197e+01 -2.05243301e+01  1.60168276e+01]]

 [[ 2.63072729e+00  1.15348747e+02  5.78124771e+01]
  [ 2.77417717e+01 -2.07163048e+01  1.58592939e+01]]], 'nanometer')>