In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import molsysmt as msm
from molsysmt import puw
import numpy as np

# Geometrical transformations

## Translations and shifts of cartesian coordinates

In [3]:
molecular_system = msm.demo_systems.metenkephalin()

In [4]:
msm.info(molecular_system)

In [5]:
coordinates = msm.get(molecular_system, coordinates=True)
coordinates

array([[[ 0.3326,  0.1548, -0.    ],
        [ 0.3909,  0.0724, -0.    ],
        [ 0.397 ,  0.2846, -0.    ],
        ...,
        [ 1.8161,  1.4927,  0.2287],
        [ 1.7833,  1.0413, -0.    ],
        [ 1.8356,  0.9301, -0.    ]]]) <Unit('nanometer')>

In [6]:
n_atoms = msm.get(molecular_system, n_atoms=True)
shifts = np.ones([n_atoms,3], dtype=float)*puw.unit('nm')

In [7]:
msm.translate(molecular_system, translation=shifts)

In [8]:
coordinates = msm.get(molecular_system, coordinates=True)
coordinates

array([[[1.3326, 1.1548, 1.    ],
        [1.3909, 1.0724, 1.    ],
        [1.397 , 1.2846, 1.    ],
        ...,
        [2.8161, 2.4927, 1.2287],
        [2.7833, 2.0413, 1.    ],
        [2.8356, 1.9301, 1.    ]]]) <Unit('nanometer')>

In [9]:
shifts = np.array([-1.0, -1.0, -1.0], dtype=float)*puw.unit('nm')
msm.translate(molecular_system, translation=shifts)

In [10]:
coordinates = msm.get(molecular_system, coordinates=True)
coordinates

array([[[0.3326, 0.1548, 0.    ],
        [0.3909, 0.0724, 0.    ],
        [0.397 , 0.2846, 0.    ],
        ...,
        [1.8161, 1.4927, 0.2287],
        [1.7833, 1.0413, 0.    ],
        [1.8356, 0.9301, 0.    ]]]) <Unit('nanometer')>

In [11]:
shifts = np.array([0.0, 0.0, 1.0], dtype=float)*puw.unit('nm')
molecular_system_2 = msm.translate(molecular_system, translation=shifts, selection=[0,1,2],
                                   in_place=False)

In [12]:
coordinates = msm.get(molecular_system_2, coordinates=True)
print(coordinates)

[[[0.3326 0.15480000000000005 1.0]  [0.3909 0.07240000000000002 1.0]  [0.397 0.28459999999999996 1.0]  ...  [1.8161 1.4927000000000001 0.2286999999999999]  [1.7832999999999997 1.0412999999999997 0.0]  [1.8356000000000003 0.9300999999999999 0.0]]] nanometer


## Shifts of dihedral angles

In [13]:
set_dihedral_angles()
shift_dihedral_angles()

NameError: name 'set_dihedral_angles' is not defined