# XXX

In [79]:
import pint as pint
import numpy as np
import pyunitwizard as puw

In [81]:
puw.configure.load_libraries(['pint', 'simtk.unit'])

In [89]:
xx = np.zeros([6,3,3])

In [86]:
xx = np.zeros([6,3,3])
xx[:,0,0]=1.0
xx[:,1,1]=1.0
xx[:,2,2]=1.0

xx = puw.quantity(xx, 'nm', 'pint')

In [87]:
units = puw.get_unit(xx)
value = puw.get_value(xx)
volume = np.linalg.det(value)*units**3

array([1., 1., 1., 1., 1., 1.]) <Unit('nanometer ** 3')>

In [24]:
xx = np.zeros([6,3,3])

In [25]:
xx[:,0,0]=1.0
xx[:,1,1]=1.0
xx[:,2,2]=1.0

In [26]:
xx = xx*pint.Unit('nm')

In [30]:
np.dot(xx[:,0,:], np.cross(xx[:,1,:], xx[:,2,:], axis=-1))

ValueError: shapes (6,3) and (6,3) not aligned: 3 (dim 1) != 6 (dim 0)

In [46]:
aa = np.cross(xx[:,1,:], xx[0,2,:], axis=-1)

In [47]:
aa.shape

(6, 3)

In [76]:
np.linalg.det(xx)

TypeError: no implementation found for 'numpy.linalg.det' on types that implement __array_function__: [<class 'pint.quantity.build_quantity_class.<locals>.Quantity'>]

In [73]:
np.dot(aa[:,:].magnitude, xx[:,0,:].magnitude.T)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [8]:
aa = np.zeros([3,6]) * pint.Unit('nm')

In [9]:
bb = np.zeros([3,6]) * pint.Unit('nm')

In [11]:
aa.magnitude

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.concatenate([aa,bb])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]]) <Unit('nanometer')>

In [6]:
aa = None * pint.Unit('nm')

TypeError: unsupported operand type(s) for *: 'Quantity' and 'NoneType'