In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import molsysmt as msm
import openinterface as oin
from matplotlib import pyplot as plt
import simtk.unit as unit
import seaborn as sns
import numpy as np

_ColormakerRegistry()

In [3]:
#molecular_system_a = msm.convert('mmtf:2GDL', 'molsysmt.MolSys')
#molecular_system_b = msm.convert('pdb:2GDL', 'molsysmt.MolSys')
#mmtf = msm.convert('pdb:2GDL', 'mmtf.MMTFDecoder')

In [4]:
molecular_system = msm.test_systems.files['trp-cage_solvated.pdb']

In [5]:
molecular_system = msm.convert(molecular_system, to_form='molsysmt.MolSys')

In [23]:
aa=[1,2,3,4]

In [24]:
msm.select(molecular_system, selection="group.index == @aa")

<class 'list'>
[1, 2, 3, 4]


array([ 9, 10, 11, ..., 50, 51, 52])

In [14]:
msm.get(molecular_system, selection="group.index == @aa", atom_name=True)

[1, 2, 3, 4]


array(['N', 'H', 'CA', ..., 'HE22', 'C', 'O'], dtype=object)

In [ ]:
msm.info(molecular_system)

In [ ]:
from numpy import unique

In [ ]:
msm.get(molecular_system, target='component', indices=0, n_groups=True)

In [ ]:
msm.multitool._get_form(molecular_system)

In [ ]:
n_groups = msm.get(molecular_system, target='component', indices=[55, 56, 57], n_groups=True)
print('Number of groups:', n_groups)

In [ ]:
molecular_system = msm.convert(molecular_system)

In [ ]:
aa=msm.get(molecular_system, target='atom', group_name=True)

In [ ]:
aa = msm.get(molecular_system, target='group', type=True)

In [ ]:
aa='water'

In [ ]:
aa.copy()

In [ ]:
bb='TYR'

In [ ]:
bb.__iter__

In [ ]:
list(map(msm.elements.group.name_to_type, aa))

In [15]:
molecular_system = msm.convert(msm.test_systems.files['HIF1_HS_Mod.pdb'])

In [26]:
import numpy as np

In [37]:
aa=np.array([0,1])

In [38]:
bb="CA"

In [42]:
msm.select(molecular_system, selection='atom.name==@bb and group.index==@aa')

bb
['C', 'A']
aa
[0, 1]


array([ 2, 11])

In [30]:
oin.contact_map(molecular_system, 'component.index == 0', 'component.index == 1')

(array([[[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]]]),
 ['GLU-10@0',
  'ARG-11@1',
  'ARG-12@2',
  'ARG-13@3',
  'ARG-14@4',
  'ASN-15@5',
  'LYS-16@6',
  'MET-17@7',
  'THR-18@8',
  'ALA-19@9',
  'TYR-20@10',
  'ILE-21@11',
  'THR-22@12',
  'GLU-23@13',
  'LEU-24@14',
  'SER-25@15',
  'ASP-26@16',
  'MET-27@17',
  'VAL-28@18',
  'PRO-29@19',
  'THR-30@20',
  'CYS-31@21',
  'SER-32@22',
  'ALA-33@23',
  'LEU-34@24',
  'ALA-35@25',
  'ARG-36@26',
  'LYS-37@27',
  'PRO-38@28',
  'ASP-39@29',
  'LYS-40@30',
  'LEU-41@31',
  'THR-42@32',
  'ILE-43@33',
  'LEU-44@34',
  'ARG-45@35',
  'MET-46@36',
  'ALA-47@37',
  'VAL-48@38',
  'SER-49@39',
  'HIS-50@40',
  'MET-51@41',
  'LYS-52@42',
