In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import molsysmt as msm
import numpy as np

# Translate

In [3]:
molecular_system = msm.demo.classes.metenkephalin(to_form='molsysmt.MolSys')

In [4]:
msm.info(molecular_system)

In [5]:
msm.get(molecular_system, coordinates=True)

array([[[ 0.3326,  0.1548, -0.    ],
        [ 0.3909,  0.0724, -0.    ],
        [ 0.397 ,  0.2846, -0.    ],
        ...,
        [ 1.8161,  1.4927,  0.2287],
        [ 1.7833,  1.0413, -0.    ],
        [ 1.8356,  0.9301, -0.    ]]]) <Unit('nanometer')>

In [6]:
n_atoms = msm.get(molecular_system, n_atoms=True)
shifts = np.ones([n_atoms,3], dtype=float)*msm.puw.unit('nm')

In [7]:
molecular_system = msm.structure.translate(molecular_system, translation=shifts)

In [8]:
coordinates = msm.get(molecular_system, coordinates=True)
coordinates

array([[[1.3326, 1.1548, 1.    ],
        [1.3909, 1.0724, 1.    ],
        [1.397 , 1.2846, 1.    ],
        ...,
        [2.8161, 2.4927, 1.2287],
        [2.7833, 2.0413, 1.    ],
        [2.8356, 1.9301, 1.    ]]]) <Unit('nanometer')>

In [9]:
shifts = np.array([-1.0, -1.0, -1.0], dtype=float)*msm.puw.unit('nm')
molecular_system = msm.structure.translate(molecular_system, translation=shifts,
                                           selection=[0,1,2], in_place=False)

In [10]:
msm.get(molecular_system, coordinates=True)

array([[[0.3326, 0.1548, 0.    ],
        [0.3909, 0.0724, 0.    ],
        [0.397 , 0.2846, 0.    ],
        ...,
        [2.8161, 2.4927, 1.2287],
        [2.7833, 2.0413, 1.    ],
        [2.8356, 1.9301, 1.    ]]]) <Unit('nanometer')>