In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
np.warnings.filterwarnings('ignore', category=np.VisibleDeprecationWarning) # Debugging: 'ignore' -> 'error'

# Hydrogen bonds

In [3]:
import molsysmt as msm

In [4]:
molecular_system = msm.demo['pentalanine']['traj.h5']
molecular_system = msm.convert(molecular_system, to_form='molsysmt.MolSys')

In [5]:
msm.info(molecular_system)

## Acceptor atoms

In [6]:
msm.hbonds.acceptor_inclusion_rules

["atom_type=='O'", "atom_type=='N'", "atom_type=='S'"]

In [7]:
msm.hbonds.acceptor_exclusion_rules

["atom_name=='NE2' and group_name=='GLN'",
 "(atom_name=='NE2' and group_name=='HIS') bonded to (atom_type=='H')",
 "(atom_name=='ND1' and group_name=='HIS') bonded to (atom_type=='H')"]

In [8]:
acceptors=msm.hbonds.get_acceptor_atoms(molecular_system)

In [9]:
acceptors

array([ 5,  6, 15, ..., 46, 55, 56])

In [10]:
msm.info(molecular_system, target='atom', selection='@acceptors')

In [11]:
acceptors=msm.hbonds.get_acceptor_atoms(molecular_system, inclusion_rules=["atom_name=='CB'"],
                                        exclusion_rules=["atom_type=='N' and group_name=='ALA'"])

In [12]:
msm.info(molecular_system, target='atom', selection='@acceptors')

In [13]:
msm.select(molecular_system, selection="all bonded to atom_type=='H'")

array([1, 6, 8, ..., 50, 56, 58], dtype=object)

In [14]:
acceptors=msm.hbonds.get_acceptor_atoms(molecular_system,
                                        default_inclusion_rules=False, default_exclusion_rules=False,
                                        inclusion_rules=["atom_type=='C'"],
                                        exclusion_rules=["all bonded to atom_type=='H'"])

In [15]:
msm.info(molecular_system, target='atom', selection='@acceptors')

## Donor atoms

In [16]:
msm.hbonds.donor_inclusion_rules

["(atom_type=='O') bonded to (atom_type=='H')",
 "(atom_type=='N') bonded to (atom_type=='H')"]

In [17]:
msm.hbonds.donor_exclusion_rules

["(atom_name=='NE2') not bonded to (atom_type=='H')",
 "(atom_name=='ND1') not bonded to (atom_type=='H')"]

In [18]:
donors = msm.hbonds.get_donor_atoms(molecular_system)

In [19]:
donors

array([[ 6,  7],
       [16, 17],
       [26, 27],
       [36, 37],
       [46, 47],
       [56, 57]])

In [20]:
msm.info(molecular_system, target='atom', selection='@donors[0]')

In [21]:
donors_heavy_atom=donors[:,0]

In [22]:
msm.info(molecular_system, target='atom', selection='@donors_heavy_atom')

# Buch

In [23]:
hbonds = msm.hbonds.buch(molecular_system)

In [24]:
len(hbonds)

7

In [25]:
hbonds.keys()

dict_keys([(6, 7, 6), (16, 17, 6), (6, 7, 5), (16, 17, 15), (16, 17, 45), (16, 17, 35), (16, 17, 55)])