In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import molmodmt as m3t
import nglview as nv
from simtk import unit
import numpy as np

/home/diego/Myopt/miniconda3/envs/UIBCDF_lab_dev/lib/python3.7/site-packages/yank/experiment.py:1170: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  """)


_ColormakerRegistry()

# Cálculo de distancias

El cálculo de distancias en MolModMT se puede hacer actualmente recurriendo a dos motores: el propio conjunto de librerías de MolMoMT programadas para tal efecto y las encontradas en la librería MDTraj (en el futuro se añadirán MDAnalysis y Pytraj). La opción por defecto, si no se especifica otra cosa, es usar el código propio de MolModMT. Si por algún motivo se prefiere realizar los cálculos empleando métodos de MDTraj, se puede añadir el argumento de entrada `engine='MDTraj'` a cada uno de los métodos que aparecen a continuación.

## Distancias simples

MolModMT acepta trabajar con matrices de coordenadas espaciales como la forma más simple de codificar las posiciones de un modelo molecular de átomos iguales, sin información topológica. Es lo que MolModMT denomina objeto `XYZ`:

In [3]:
model_A = np.zeros([6,3], dtype='float64') * unit.angstroms

In [4]:
m3t.get_form(model_A)

'XYZ'

In [5]:
m3t.get(model_A, n_frames=True, n_atoms=True)

[1, 6]

El objeto XYZ debe ser un tensor de tipo array de numpy de rango 3 o 2 según sea: [índice_frame, indice_átomo, coordenada] o [índice_atómo, coordenada], donde coordenada es x, y o z. Es obligatorio que este array de numpy lleve unidades de longitud.

In [6]:
model_A = np.zeros([2,4,3], dtype='float64') * unit.nanometers

In [7]:
m3t.get(model_A, n_frames=True, n_atoms=True)

[2, 4]

### Distancia simple entre puntos

El caso más sencillo que podemos resolver en cuanto al cálculo de distancias es el de la distancia entre los puntos de un conjunto, o entre dos conjuntos distintos de puntos en el espacio, sin condiciones de contorno periódicas. 

#### Caso 1

Supongamos un conjunto único conjunto de tres puntos con coordenadas que adjudicaremos arbitrariamente a modo de ejemplo:

In [8]:
set_A = np.zeros([1,3,3], dtype='float64') * unit.nanometers

set_A[0,0,:] = [0, 2, -1] * unit.nanometers
set_A[0,1,:] = [-1, 1, 1] * unit.nanometers
set_A[0,2,:] = [-2, 0, 1] * unit.nanometers

Podemos calcular la distancia entre los elementos de `set_A` como:

In [9]:
distances = m3t.distance(item_1=set_A)

In [10]:
distances

Quantity(value=array([[[0.        , 2.44948974, 3.46410162],
        [2.44948974, 0.        , 1.41421356],
        [3.46410162, 1.41421356, 0.        ]]]), unit=nanometer)

De tal manera que la distancia entre el elemento 0-ésimo y el 2-ésimo en el único frame 0-ésimo es:

In [12]:
print(distances[0,0,2])

3.4641016151377544 nm


Si quisíeramos haber calculado únicamente la distancia entre esos dos elementos podríamos haber recurrido a:

In [13]:
distances = m3t.distance(item_1=set_A, selection_1=0, selection_2=2)

In [14]:
print(distances)

[[[3.46410162]]] nm


Observa que la forma del array es un tensor de rango 3 donde en este caso todas las dimensiones son iguales a 1:

In [15]:
distances.shape

(1, 1, 1)

Esto es porque en este caso sólo tenemos un frame (primer rango) con dos listas de elementos (segundo y tercer rango): `selection_1` y `selection_2`. Y en este caso ambas listas contienen un único elemento, el 0-ésimo en el primer caso y el 2-ésimo en el segundo. Veamos ahora qué pasa si queremos calcular la distancia entre el elemento 0-ésimo y los otros dos:

In [16]:
distances = m3t.distance(item_1=set_A, selection_1=0, selection_2=[1,2])

In [17]:
distances.shape

(1, 1, 2)

El tensor de distancias tiene ahora dimensión 2 en el último rango. ¿Cómo entonces por ejemplo veríamos cúal es la distancia entre el elemento 0-ésimo y el 2-ésimo en el único frame que tenemos según el actual objeto `distances`? 

In [18]:
print(distances[0,0,1])

3.4641016151377544 nm


Para mayor claridad podemos también obtener el resultado del método `molmodmt.distance` como diccionario, donde ahora sí podemos recurrir al índice de elemento expresado en los argumentos `selection_1` y `selection_2`:

In [19]:
distances = m3t.distance(item_1=set_A, selection_1=0, selection_2=[1,2], output_form='dict')

In [20]:
print(distances)

{0: {1: Quantity(value=array([2.44948974]), unit=nanometer), 2: Quantity(value=array([3.46410162]), unit=nanometer)}}


En realidad el objeto `distances` es ahora un diccionario de diccionarios para poder rápidamente conocer las distancias entre dos elementos en función del índice de frame. Veamos cómo acceder a la lista de distancias para los diferentes frames (aquí sólo uno) entre el elemento 0-ésimo incluido en `selection_1` y el 2-ésimo incluido en `selection_2`:

In [21]:
print(distances[0][2])

[3.46410162] nm


#### Caso 2

Supongamos ahora que tenemos dos conjuntos de puntos en el espacio en tres instantes de tiempo: `set_A` con tres elementos y `set_B` con dos.

In [30]:
# Set_A inicializado a cero:
set_A = np.zeros([3,3,3], dtype='float64') * unit.nanometers

## coordenadas del primer elemento de Set_A para los tres frames 
set_A[0,0,:] = [0, 2, -1] * unit.nanometers
set_A[1,0,:] = [1, 2, -1] * unit.nanometers
set_A[2,0,:] = [0, 2, -1] * unit.nanometers

## coordenadas del segundo elemento de Set_A para los tres frames
set_A[0,1,:] = [-1, 1, 1] * unit.nanometers
set_A[1,1,:] = [-1, 0, 1] * unit.nanometers
set_A[2,1,:] = [0, 0, 1] * unit.nanometers

## coordenadas del tercer elemento de Set_A para los tres frames
set_A[0,2,:] = [-2, 0, 1] * unit.nanometers
set_A[1,2,:] = [-2, 0, 0] * unit.nanometers
set_A[2,2,:] = [-1, 1, 0] * unit.nanometers

# Set_B inicializado a cero:

set_B = np.zeros([3,2,3], dtype='float64') * unit.nanometers

## coordenadas del primer elemento de Set_B para los tres frames
set_B[0,0,:] = [4, -2, 0] * unit.nanometers
set_B[1,0,:] = [5, -2, -1] * unit.nanometers
set_B[2,0,:] = [5, -2, 0] * unit.nanometers

## coordenadas del segundo elemento de Set_B para los tres frames
set_B[0,1,:] = [3, 0, -1] * unit.nanometers
set_B[1,1,:] = [3, 1, 0] * unit.nanometers
set_B[2,1,:] = [4, 1, 1] * unit.nanometers

Podemos ahora invocando una sola vez el método `molmodmt.distance` calcular todas las distancias entre los elementos de ambos conjuntos para todos los frames:

In [31]:
distances = m3t.distance(item_1=set_A, item_2=set_B)

De esta manera podemos por ejemplo acceder a la distancia entre el elemento 2-ésimo de `set_A` y el elemento 0-ésimo de `set_B` para el segundo frame o frame 1-ésimo.

In [32]:
print(distances[1,2,0])

7.3484692283495345 nm


O imprimir esta distancia en función para todos los frames:

In [33]:
print(distances[:,2,0])

[6.40312424 7.34846923 6.70820393] nm


Como vimos en el caso anterior, podemos ordenar que la salida del método `molmodmt.distance` sea en forma de diccionario de diccionarios.

In [34]:
distances = m3t.distance(item_1=set_A, item_2=set_B, output_form='dict')

Podemos entonces acceder a las mismas distancias que anteriormente:

In [35]:
# distancia entre el elemento 2-ésimo de set_A y 0-ésimo para el segundo frame
print(distances[2][0][1])

7.3484692283495345 nm


In [36]:
# distancia entre el elemento 2-ésimo de set_A y 0-ésimo en cada frame
print(distances[2][0])

[6.40312424 7.34846923 6.70820393] nm


Esta manera de sacar los datos puede ser muy conveniente cuando calculamos distancias entre listas de elementos de ambos conjuntos. Supongamos que queremos calcular las distancias entre los elementos 1-ésimo y 2-ésimo de `set_A` y el elemento 1-ésimo de `set_B` para todos los frames. Primero veamos cómo hacerlo con la salida tipo tensor (salida por defecto):

In [37]:
distances = m3t.distance(item_1=set_A, selection_1=[1,2], item_2=set_B, selection_2=1)

De esta manera las distancias por ejemplo para ambos frames entre el elemento 2-ésimo de `set_A` con el elemento 1-ésimo de `set_B` se situan ahora en la posición 1-ésima (por ser el 1-ésimo elemento de la lista `selection_1`) frente a la 0-ésima (por ser el elemento 0-ésimo elemento, único en este caso, de la lista `selection_2`) en el segundo y tercer rango del tensor correspondientemente:

In [38]:
print(distances[:,1,0])

[5.38516481 5.09901951 5.09901951] nm


La salida de `molmodmt.distances` tipo diccionario de diccionarios puede hacer más cómodo el trabajo con las distancias resultado, ya que el diccionario recupera los índices iniciales de cada elemento en ambos conjuntos `set_A` y `set_B`.

In [39]:
distances = m3t.distance(item_1=set_A, selection_1=[1,2], item_2=set_B, selection_2=1, output_form='dict')

La lista de distancias para los distintos frames entre el elemento 2-ésimo de `set_A` y el 1-ésimo de `set_B`, las mismas que anteriormente, puede ser encontrada según: 

In [40]:
print(distances[2][1])

[5.38516481 5.09901951 5.09901951] nm


Por último, supongamos que únicamente queremos calcular la distancia entre estas dos últimas selecciones para el frame 0-ésimo y el 2-ésimo. Podemos incluir también como argumento de entrada en `molmodmt.distance` la selección de una lista de frames:

In [41]:
distances = m3t.distance(item_1=set_A, selection_1=[1,2], item_2=set_B, selection_2=1, frame_indices_1=[0,2])

In [42]:
distances.shape

(3, 2, 1)

In [ ]:
distances = m3t.distance(item_1=set_A, selection_1=[1,2], item_2=set_B, selection_2=1,
                         frame_indices=[0,2], output_form='dict')

## Distancias máximas y mínimas

## Distancias entre grupos 

## Listas de vecinos

## Mapas de contactos

In [ ]:
molsys = m3t.load('/home/diego/1brs.pdb', selection='chainid 0 or chainid 3')

In [ ]:
m3t.view(molsys)

In [ ]:
dists_CAs = m3t.distance(molsys, selection_1="chainid 0 and name CA", selection_2="chainid 3 and name CA")

In [ ]:
chain0_CAs = m3t.select(molsys, "chainid 0 and name CA")
chain3_CAs = m3t.select(molsys, "chainid 3 and name CA")

ii=10
jj=20
frame_index=0

print('La distancia entre el átomo {} y el átomo {} es {}'.format(chain0_CAs[ii], chain3_CAs[jj], dists_CAs[frame_index,ii,jj]))

In [ ]:
dists_CAs = m3t.distance(molsys, selection_1="chainid 0 and name CA", selection_2="chainid 3 and name CA", output_form='dict')

In [ ]:
ii=74
jj=1022
frame_index=0

print('La distancia entre el átomo {} y el átomo {} es {}'.format(ii, jj, dists_CAs[ii][jj][frame_index]))

In [ ]:
m3t.get(molsys, target='atom', indices=[74,1022], index=True, id=True, name=True, element=True)