In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import molmodmt as m3t
import nglview as nv
from simtk import unit
import numpy as np

/home/diego/Myusr/opt/miniconda3/envs/UIBCDF_lab_dev/lib/python3.7/site-packages/yank-0.24.2-py3.7-linux-x86_64.egg/yank/experiment.py:1170: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  """)


_ColormakerRegistry()

# Cálculo de distancias

El cálculo de distancias en MolModMT se puede hacer actualmente recurriendo a dos motores: el propio conjunto de librerías de MolMoMT programadas para tal efecto y las encontradas en la librería MDTraj (en el futuro se añadirán MDAnalysis y Pytraj). La opción por defecto, si no se especifica otra cosa, es usar el código propio de MolModMT. Si por algún motivo se prefiere realizar los cálculos empleando métodos de MDTraj, se puede añadir el argumento de entrada `engine='MDTraj'` a cada uno de los métodos que aparecen a continuación.

## Distancias simples

MolModMT acepta trabajar con matrices de coordenadas espaciales como la forma más simple de codificar las posiciones de un modelo molecular de átomos iguales, sin información topológica. Es lo que MolModMT denomina objeto `XYZ`:

In [3]:
model_A = np.zeros([6,3], dtype='float64') * unit.angstroms

In [4]:
m3t.get_form(model_A)

'XYZ'

In [5]:
m3t.get(model_A, n_frames=True, n_atoms=True)

[1, 6]

El objeto XYZ debe ser un tensor de tipo array de numpy de rango 3 o 2 según sea: [índice_frame, indice_átomo, coordenada] o [índice_atómo, coordenada], donde coordenada es x, y o z. Es obligatorio que este array de numpy lleve unidades de longitud.

In [6]:
model_A = np.zeros([2,4,3], dtype='float64') * unit.nanometers

In [7]:
m3t.get(model_A, n_frames=True, n_atoms=True)

[2, 4]

### Distancia simple entre puntos

El caso más sencillo que podemos resolver en cuanto al cálculo de distancias es el de la distancia entre los puntos de un conjunto, o entre dos conjuntos distintos de puntos en el espacio, sin condiciones de contorno periódicas. 

#### Caso 1

Supongamos un conjunto único conjunto de tres puntos con coordenadas que adjudicaremos arbitrariamente a modo de ejemplo:

In [8]:
set_A = np.zeros([1,3,3], dtype='float64') * unit.nanometers

set_A[0,0,:] = [0, 2, -1] * unit.nanometers
set_A[0,1,:] = [-1, 1, 1] * unit.nanometers
set_A[0,2,:] = [-2, 0, 1] * unit.nanometers

Podemos calcular la distancia entre los elementos de `set_A` como:

In [9]:
distances = m3t.distance(item_1=set_A)

In [10]:
distances

Quantity(value=array([[[0.        , 2.44948974, 3.46410162],
        [2.44948974, 0.        , 1.41421356],
        [3.46410162, 1.41421356, 0.        ]]]), unit=nanometer)

El resultado es un tensor de rango 3 donde el primer rango es el índice de frame, en este caso no hay más que uno, y el segundo y el tercer rango corresponden a los indices de los elementos de `set_A`:

In [11]:
distances.shape

(1, 3, 3)

De tal manera que la distancia entre el elemento 0-ésimo y el 2-ésimo en el único frame 0-ésimo es:

In [12]:
print(distances[0,0,2])

3.4641016151377544 nm


Si quisíeramos haber calculado únicamente la distancia entre esos dos elementos podríamos haber recurrido a:

In [13]:
distances = m3t.distance(item_1=set_A, selection_1=0, selection_2=2)

In [14]:
print(distances)

[[[3.46410162]]] nm


Observa que la forma del array es un tensor de rango 3 donde en este caso todas las dimensiones son iguales a 1:

In [15]:
distances.shape

(1, 1, 1)

Esto es porque en este caso sólo tenemos un frame (primer rango) con dos listas de elementos (segundo y tercer rango): `selection_1` y `selection_2`. Y en este caso ambas listas contienen un único elemento, el 0-ésimo en el primer caso y el 2-ésimo en el segundo. Veamos ahora qué pasa si queremos calcular la distancia entre el elemento 0-ésimo y los otros dos:

In [16]:
distances = m3t.distance(item_1=set_A, selection_1=0, selection_2=[1,2])

In [17]:
distances.shape

(1, 1, 2)

El tensor de distancias tiene ahora dimensión 2 en el último rango. ¿Cómo entonces por ejemplo veríamos cúal es la distancia entre el elemento 0-ésimo y el 2-ésimo en el único frame que tenemos según el actual objeto `distances`? 

In [18]:
print(distances[0,0,1])

3.4641016151377544 nm


Para mayor claridad podemos también obtener el resultado del método `molmodmt.distance` como diccionario, donde ahora sí podemos recurrir al índice de elemento expresado en los argumentos `selection_1` y `selection_2`:

In [19]:
distances = m3t.distance(item_1=set_A, selection_1=0, selection_2=[1,2], output_form='dict')

In [20]:
print(distances)

{0: {1: Quantity(value=array([2.44948974]), unit=nanometer), 2: Quantity(value=array([3.46410162]), unit=nanometer)}}


En realidad el objeto `distances` es ahora un diccionario de diccionarios para poder rápidamente conocer las distancias entre dos elementos en función del índice de frame. Veamos cómo acceder a la lista de distancias para los diferentes frames (aquí sólo uno) entre el elemento 0-ésimo incluido en `selection_1` y el 2-ésimo incluido en `selection_2`:

In [21]:
print(distances[0][2])

[3.46410162] nm


#### Caso 2

Supongamos ahora que tenemos dos conjuntos de puntos en el espacio en tres instantes de tiempo: `set_A` con tres elementos y `set_B` con dos.

In [22]:
# Set_A inicializado a cero:
set_A = np.zeros([3,3,3], dtype='float64') * unit.nanometers

## coordenadas del primer elemento de Set_A para los tres frames 
set_A[0,0,:] = [0, 2, -1] * unit.nanometers
set_A[1,0,:] = [1, 2, -1] * unit.nanometers
set_A[2,0,:] = [0, 2, -1] * unit.nanometers

## coordenadas del segundo elemento de Set_A para los tres frames
set_A[0,1,:] = [-1, 1, 1] * unit.nanometers
set_A[1,1,:] = [-1, 0, 1] * unit.nanometers
set_A[2,1,:] = [0, 0, 1] * unit.nanometers

## coordenadas del tercer elemento de Set_A para los tres frames
set_A[0,2,:] = [-2, 0, 1] * unit.nanometers
set_A[1,2,:] = [-2, 0, 0] * unit.nanometers
set_A[2,2,:] = [-1, 1, 0] * unit.nanometers

# Set_B inicializado a cero:

set_B = np.zeros([3,2,3], dtype='float64') * unit.nanometers

## coordenadas del primer elemento de Set_B para los tres frames
set_B[0,0,:] = [4, -2, 0] * unit.nanometers
set_B[1,0,:] = [5, -2, -1] * unit.nanometers
set_B[2,0,:] = [5, -2, 0] * unit.nanometers

## coordenadas del segundo elemento de Set_B para los tres frames
set_B[0,1,:] = [3, 0, -1] * unit.nanometers
set_B[1,1,:] = [3, 1, 0] * unit.nanometers
set_B[2,1,:] = [4, 1, 1] * unit.nanometers

Podemos ahora invocando una sola vez el método `molmodmt.distance` calcular todas las distancias entre los elementos de ambos conjuntos para todos los frames:

In [23]:
distances = m3t.distance(item_1=set_A, item_2=set_B)

De esta manera podemos por ejemplo acceder a la distancia entre el elemento 2-ésimo de `set_A` y el elemento 0-ésimo de `set_B` para el segundo frame o frame 1-ésimo.

In [24]:
print(distances[1,2,0])

7.3484692283495345 nm


O imprimir esta distancia en función para todos los frames:

In [25]:
print(distances[:,2,0])

[6.40312424 7.34846923 6.70820393] nm


Como vimos en el caso anterior, podemos ordenar que la salida del método `molmodmt.distance` sea en forma de diccionario de diccionarios.

In [26]:
distances = m3t.distance(item_1=set_A, item_2=set_B, output_form='dict')

Podemos entonces acceder a las mismas distancias que anteriormente:

In [27]:
# distancia entre el elemento 2-ésimo de set_A y 0-ésimo para el segundo frame
print(distances[2][0][1])

7.3484692283495345 nm


In [28]:
# distancia entre el elemento 2-ésimo de set_A y 0-ésimo en cada frame
print(distances[2][0])

[6.40312424 7.34846923 6.70820393] nm


Esta manera de sacar los datos puede ser muy conveniente cuando calculamos distancias entre listas de elementos de ambos conjuntos. Supongamos que queremos calcular las distancias entre los elementos 1-ésimo y 2-ésimo de `set_A` y el elemento 1-ésimo de `set_B` para todos los frames. Primero veamos cómo hacerlo con la salida tipo tensor (salida por defecto):

In [29]:
distances = m3t.distance(item_1=set_A, selection_1=[1,2], item_2=set_B, selection_2=1)

De esta manera las distancias por ejemplo para ambos frames entre el elemento 2-ésimo de `set_A` con el elemento 1-ésimo de `set_B` se situan ahora en la posición 1-ésima (por ser el 1-ésimo elemento de la lista `selection_1`) frente a la 0-ésima (por ser el elemento 0-ésimo elemento, único en este caso, de la lista `selection_2`) en el segundo y tercer rango del tensor correspondientemente:

In [30]:
print(distances[:,1,0])

[5.38516481 5.09901951 5.09901951] nm


La salida de `molmodmt.distances` tipo diccionario de diccionarios puede hacer más cómodo el trabajo con las distancias resultado, ya que el diccionario recupera los índices iniciales de cada elemento en ambos conjuntos `set_A` y `set_B`.

In [31]:
distances = m3t.distance(item_1=set_A, selection_1=[1,2], item_2=set_B, selection_2=1, output_form='dict')

La lista de distancias para los distintos frames entre el elemento 2-ésimo de `set_A` y el 1-ésimo de `set_B`, las mismas que anteriormente, puede ser encontrada según: 

In [32]:
print(distances[2][1])

[5.38516481 5.09901951 5.09901951] nm


Por último, supongamos que únicamente queremos calcular la distancia entre estas dos últimas selecciones para el frame 0-ésimo y el 2-ésimo. Podemos incluir también como argumento de entrada en `molmodmt.distance` la selección de una lista de frames:

In [42]:
distances = m3t.distance(item_1=set_A, selection_1=[1,2], frame_indices_1=[0,2],
                         item_2=set_B, selection_2=1, frame_indices_2=[0,2])

Esta vez el resultado es un tensor donde ahora ya no tiene dimensión 3 en el primer rango, sino 2 (dos frames):

In [43]:
distances.shape

(2, 2, 1)

Supongamos que queremos acceder a la distancia entre el elemento 2-ésimo de `set_A` con el elemento 1-ésimo de `set_B` en el frame 2-ésimo:

In [45]:
print(distances[1,1,0])

5.0990195135927845 nm


Puedes comprobar que dado que `frame_indices_1` y `frame_indices_2` son iguales, puedes prescindir de `frame_indices_2`. El resultado será el mismo ya que el método sobreentiende que se trata de la misma selección de índices de frame cuando `frame_indices_2=None` y calcula las distancias entre las respectivas selecciones de elementos de ambos items en cada uno de los frames indicados únicamente en `frame_indices_1`:

In [47]:
distances = m3t.distance(item_1=set_A, selection_1=[1,2], frame_indices_1=[0,2],
                         item_2=set_B, selection_2=1)

In [48]:
distances.shape

(2, 2, 1)

En esta situación en la que estamos incluyendo una lista de indices de frames, la salida de `molmodmt.distance` en forma de diccionario de diccionarios tambien respeta los índices originales en el caso de los frames:

In [49]:
distances = m3t.distance(item_1=set_A, selection_1=[1,2], frame_indices_1=[0,2],
                         item_2=set_B, selection_2=1, output_form='dict')

Ahora podemos conocer las distancias entre dos elementos en un frame determinado sin tener que acudir a los indices de dichos elementos y frame que tienen en las listas `selection_1`, `selection_2` y `frame_indices_1`. Basta con los índices absolutos originales que para el caso anterior son 2-ésimo de `set_A` y 1-ésimo de `set_B` en el frame 2-ésimo:

In [51]:
print(distances[2][1][2])

5.0990195135927845 nm


## Distancias de desplazamiento o distancias entre distintas selecciones de índices de frame

La final de la sección anterior vimos cómo podemos hacer una selección de índices de frame cuando calculamos las distancias entre los elementos de dos modelos moleculares (objetos XYZ aquí). Podríamos ahora, por ejemplo, con lo aprendido hasta aquí calcular la distancia entre la selección `selection_1` del `item_1` en un cierto frame, por ejemplo el 0-ésimo, y la selección `selection_2` del `item_2` en otro cierto frame, por ejemplo el 2-ésimo:

In [53]:
distances = m3t.distance(item_1=set_A, selection_1=[1,2], frame_indices_1=0,
                         item_2=set_B, selection_2=1, frame_indices_2=2)

In [54]:
distances.shape

(1, 2, 1)

In [64]:
print('La distancia entre el elemento 2-ésimo del set_A en el frame 0 y el elemento 1-ésimo del set_B\
 en el frame 2 es {}'.format(distances[0,1,0]))

La distancia entre el elemento 2-ésimo del set_A en el frame 0 y el elemento 1-ésimo del set_Ben el frame 2 es 6.082762530298219 nm


O atendiendo a dos listas de índices de frames que serán enfrentadas secuencialmente: primer elemento de la primera lista frente a primer elemento de la segunda lista, segundo frente a segundo, y así consecutivamente:

In [65]:
distances = m3t.distance(item_1=set_A, selection_1=[1,2], frame_indices_1=[0,1],
                         item_2=set_B, selection_2=1, frame_indices_2=[1,2])

In [66]:
distances.shape

(2, 2, 1)

In [68]:
print('La distancia entre el elemento 2-ésimo del set_A en el frame 0 y el elemento 1-ésimo del set_B\
 en el frame 1 es {}'.format(distances[0,1,0]))
print('La distancia entre el elemento 2-ésimo del set_A en el frame 1 y el elemento 1-ésimo del set_B\
 en el frame 2 es {}'.format(distances[1,1,0]))

La distancia entre el elemento 2-ésimo del set_A en el frame 0 y el elemento 1-ésimo del set_B en el frame 1 es 5.196152422706632 nm
La distancia entre el elemento 2-ésimo del set_A en el frame 1 y el elemento 1-ésimo del set_B en el frame 2 es 6.164414002968976 nm


O el mismo cálculo con su salida en forma de diccionario:

In [70]:
distances = m3t.distance(item_1=set_A, selection_1=[1,2], frame_indices_1=[0,1],
                         item_2=set_B, selection_2=1, frame_indices_2=[1,2], output_form='dict')

Donde dado que la relación entre índices de frame es uno a uno (el 0-ésimo de `set_A` frente al 1-ésimo de `set_B` y el 1-ésimo de `set_A` frente al 2-ésimo de `set_B`, en este caso), el diccionario resultante apela únicamente al índice original de `frame_indices_1`:

In [71]:
print('La distancia entre el elemento 2-ésimo del set_A en el frame 0 y el elemento 1-ésimo del set_B\
 en el frame 1 es {}'.format(distances[2][1][0]))
print('La distancia entre el elemento 2-ésimo del set_A en el frame 1 y el elemento 1-ésimo del set_B\
 en el frame 2 es {}'.format(distances[2][1][1]))

La distancia entre el elemento 2-ésimo del set_A en el frame 0 y el elemento 1-ésimo del set_B en el frame 1 es 5.196152422706632 nm
La distancia entre el elemento 2-ésimo del set_A en el frame 1 y el elemento 1-ésimo del set_B en el frame 2 es 6.164414002968976 nm


De esta manera podríamos incluso enfrentar ciertos elementos del set_A en todos sus frames contra ciertos elementos de set_B de un mismo frame, por ejemplo frente al 0-ésimo.

In [73]:
distances = m3t.distance(item_1=set_A, selection_1=[0,1,2], frame_indices_1=[0,1,2],
                         item_2=set_B, selection_2=1, frame_indices_2=[0,0,0])

In [74]:
distances.shape

(3, 3, 1)

In [75]:
print('La distancia entre el elemento 2-ésimo del set_A en el frame 0 y el elemento 1-ésimo del set_B\
 en el frame 0 es {}'.format(distances[0,2,0]))
print('La distancia entre el elemento 2-ésimo del set_A en el frame 1 y el elemento 1-ésimo del set_B\
 en el frame 0 es {}'.format(distances[1,2,0]))
print('La distancia entre el elemento 2-ésimo del set_A en el frame 2 y el elemento 1-ésimo del set_B\
 en el frame 0 es {}'.format(distances[2,2,0]))

La distancia entre el elemento 2-ésimo del set_A en el frame 0 y el elemento 1-ésimo del set_B en el frame 0 es 5.385164807134504 nm
La distancia entre el elemento 2-ésimo del set_A en el frame 1 y el elemento 1-ésimo del set_B en el frame 0 es 5.0990195135927845 nm
La distancia entre el elemento 2-ésimo del set_A en el frame 2 y el elemento 1-ésimo del set_B en el frame 0 es 4.242640687119285 nm


O igualmente:

In [76]:
distances = m3t.distance(item_1=set_A, selection_1=[0,1,2], frame_indices_1=[0,1,2],
                         item_2=set_B, selection_2=1, frame_indices_2=[0,0,0], output_form='dict')

In [77]:
print('La distancia entre el elemento 2-ésimo del set_A en el frame 0 y el elemento 1-ésimo del set_B\
 en el frame 0 es {}'.format(distances[2][1][0]))
print('La distancia entre el elemento 2-ésimo del set_A en el frame 1 y el elemento 1-ésimo del set_B\
 en el frame 0 es {}'.format(distances[2][1][1]))
print('La distancia entre el elemento 2-ésimo del set_A en el frame 2 y el elemento 1-ésimo del set_B\
 en el frame 0 es {}'.format(distances[2][1][2]))

La distancia entre el elemento 2-ésimo del set_A en el frame 0 y el elemento 1-ésimo del set_B en el frame 0 es 5.385164807134504 nm
La distancia entre el elemento 2-ésimo del set_A en el frame 1 y el elemento 1-ésimo del set_B en el frame 0 es 5.0990195135927845 nm
La distancia entre el elemento 2-ésimo del set_A en el frame 2 y el elemento 1-ésimo del set_B en el frame 0 es 4.242640687119285 nm


Ya podemos entonces hacer el ejercicio de calcular distancias de desplazamiento de unos mismos elementos entre frames. Por ejemplo, veamos como podríamos responder la pregunta: ¿Cuanto se desplazan los elementos de `set_A` entre frames consecutivos?

In [84]:
distances = m3t.distance(item_1=set_A, frame_indices_1=[0,1], frame_indices_2=[1,2])

Podemos ahora ver cuanto se desplazó por ejemplo el elemento 1-ésimo de `set_A` entre los frames 0-ésimo y 1-ésimo, o entre el 1-ésimo y el 2-esimo.

In [86]:
print('La distancia de desplazamiento del elemento 1-ésimo de set_A entre los frames 0 y 1 es {}'.format(distances[0][1][1]))
print('La distancia de desplazamiento del elemento 1-ésimo de set_A entre los frames 1 y 2 es {}'.format(distances[1][1][1]))

La distancia de desplazamiento del elemento 1-ésimo de set_A entre los frames 0 y 1 es 1.0 nm
La distancia de desplazamiento del elemento 1-ésimo de set_A entre los frames 1 y 2 es 1.0 nm


El inconveniente que puede tener esta aproximación al cálculo de distancias de desplazamientos es que es absurdamente cara computacionalmente ya que también hemos tenido que calcular la distancia entre elementos distintos en frames distintos. O dicho de otra manera, para calcular la distancia de 3 elementos entre dos frames hemos tenido que calcular 9 distancias:

In [87]:
distances.shape

(2, 3, 3)

No tienen en este último caso mucho sentido los elementos fuera de la diagonal de la matriz `distances[0,:,:]`. ¿Qué significa la distancia entre la posición del elemento 0-ésimo en el frame 0-ésimo y la posición del elemento 2-ésimo en el frame 1-ésimo, por ejemplo?

In [89]:
distances[0,0,2] # En principio no tienen mucho sentido físicamente estos valores cruzados

Quantity(value=3.0, unit=nanometer)

Veamos en la siguiente sección como podríamos haber calculado el desplazamiento de los distintos elementos de `set_A` entre distintos frames sin necesidad de calcular los cruces entre distintos elementos del mismo objeto.

## Distancias entre pares

## Distancias máximas y mínimas

## Distancias entre grupos 

## Listas de vecinos

## Mapas de contactos

In [ ]:
molsys = m3t.load('/home/diego/1brs.pdb', selection='chainid 0 or chainid 3')

In [ ]:
m3t.view(molsys)

In [ ]:
dists_CAs = m3t.distance(molsys, selection_1="chainid 0 and name CA", selection_2="chainid 3 and name CA")

In [ ]:
chain0_CAs = m3t.select(molsys, "chainid 0 and name CA")
chain3_CAs = m3t.select(molsys, "chainid 3 and name CA")

ii=10
jj=20
frame_index=0

print('La distancia entre el átomo {} y el átomo {} es {}'.format(chain0_CAs[ii], chain3_CAs[jj], dists_CAs[frame_index,ii,jj]))

In [ ]:
dists_CAs = m3t.distance(molsys, selection_1="chainid 0 and name CA", selection_2="chainid 3 and name CA", output_form='dict')

In [ ]:
ii=74
jj=1022
frame_index=0

print('La distancia entre el átomo {} y el átomo {} es {}'.format(ii, jj, dists_CAs[ii][jj][frame_index]))

In [ ]:
m3t.get(molsys, target='atom', indices=[74,1022], index=True, id=True, name=True, element=True)