In [1]:
%load_ext autoreload
%autoreload 2

# Introduction

Goals:
   * decrease the learning barrier of new lab students
   * implement in this central repo daily useful workflows
   * A swiss army knife

In [2]:
import molmodmt as molmodmt
import os

In [3]:
molmodmt.utils.examples.pdb

{'1l2y': '/home/diego/Projects/LabTools/MolModMT/molmodmt/utils/data/pdb/1l2y.pdb',
 '1li2': '/home/diego/Projects/LabTools/MolModMT/molmodmt/utils/data/pdb/1li2.pdb'}

In [4]:
molmodmt.utils.examples.mol2

{'caffeine': '/home/diego/Projects/LabTools/MolModMT/molmodmt/utils/data/mol2/caffeine.mol2'}

In [5]:
PDB_example_file = molmodmt.utils.examples.pdb['1l2y']
MOL2_example_file = molmodmt.utils.examples.mol2['caffeine']

## Lists of engines, files and classes MolSysMT can work with.

In [6]:
molmodmt.info_forms()

{'engines': ['mdanalysis',
  'mdtraj',
  'modeller',
  'native',
  'openmm',
  'parmed',
  'pdbfixer'],
 'classes': ['mdanalysis.Universe',
  'mdtraj.Topology',
  'mdtraj.Trajectory',
  'modeller.Modeller',
  'moldyn.Native',
  'molsys.Native',
  'openmm.Positions',
  'openmm.Topology',
  'parmed.Structure',
  'pdbfixer.PDBFixer',
  'yank.Topography'],
 'files': ['ddb', 'h5', 'mol2', 'pdb', 'sdf', 'smi', 'xtc'],
 'ids': ['pdb:id']}

## Loading systems

In [7]:
molmodmt.info_load(to_form='pdb')

['mdanalysis.Universe', 'mdtraj.Trajectory', 'mol2', 'molsys.Native', 'parmed', 'pdb:id']


In [8]:
molmodmt.info_load(from_form='pdbfixer')

['mdtraj']


In [9]:
system_pdbfixer = molmodmt.load(PDB_example_file,'pdbfixer')
molmodmt.get_form(system_pdbfixer)

'pdbfixer.PDBFixer'

## Fetching molecular systems from the PDB

PDB files can be fetched and loaded straight as a PDBFixer (`pdbfixer`), MDTraj (`mdtraj`), OpenMM (`openmm`), ParmED (`parmed`), MDAnalysis (`mdanalysis`) or native (`native`) system. Where the "native" term means the main class take as base object by `MolSysSAK` -Includes a ParmED structure, a YANK topography and an MDTraj or OpenMM Topology-.

***I have to include msmt.fetch(item) where item is `pdb:id, and any other id...`***

In [10]:
PDB_id = 'pdb:1sux'
system_parmed = molmodmt.fetch(PDB_id,'parmed')
molmodmt.get_form(system_parmed)

'parmed.Structure'

In [11]:
PDB_id = 'pdb:1sux'
out_PDB_file = '1sux.pdb'
molmodmt.fetch(PDB_id,out_PDB_file)

In [12]:
os.listdir('.')

['examples_MolSys',
 '.ipynb_checkpoints',
 'examples_MolDyn',
 'Introduction.ipynb',
 '1sux.pdb']

In [13]:
#less 1sux.pdb

In [14]:
os.remove(out_PDB_file)

In [15]:
os.listdir('.')

['examples_MolSys',
 '.ipynb_checkpoints',
 'examples_MolDyn',
 'Introduction.ipynb']

## Getting the form of an item

In [16]:
system_unknown_form = molmodmt.load(PDB_example_file,'pdbfixer')
molmodmt.get_form(system_unknown_form)

'pdbfixer.PDBFixer'

In [17]:
molmodmt.get_form("PDB:1sux")

'pdb:id'

In [18]:
molmodmt.get_form(MOL2_example_file)

'mol2'

## Converting items

Files can be converted into files:

In [19]:
molmodmt.convert(PDB_example_file,'foo.mol2')

In [20]:
os.listdir('.')

['examples_MolSys',
 '.ipynb_checkpoints',
 'examples_MolDyn',
 'Introduction.ipynb',
 'foo.mol2']

In [21]:
#less foo.mol2

In [22]:
os.remove('foo.mol2')

In general, molecular system's forms can be converted into other forms: 

In [23]:
molmodmt.info_convert(from_form='parmed')

['mol2', 'pdb']


In [24]:
molmodmt.info_convert(to_form='pdb')

['mdanalysis.Universe', 'mdtraj.Trajectory', 'mol2', 'molsys.Native', 'parmed', 'pdb:id']


In [25]:
molmodmt.info_convert()

From... to...
openmm :  ['nglview']
native :  []
mdtraj :  []
parmed :  ['mol2', 'pdb']
mdanalysis :  ['nglview']
pdbfixer :  ['mdtraj']
modeller :  ['mdtraj']
mdtraj.Trajectory :  ['mdtraj.Topology', 'native.Native', 'nglview', 'openmm.Topology', 'parmed.Structure', 'pdb', 'yank.Topography']
molsys.Native :  ['mdtraj', 'mdtraj.Topology', 'mdtraj.Trajectory', 'nglview', 'openmm.Topology', 'pdb']
yank.Topography :  ['openmm.Topology']
openmm.Positions :  []
modeller.Modeller :  ['mdtraj', 'mdtraj.Topology', 'nglview', 'parmed.Structure']
pdbfixer.PDBFixer :  ['mdtraj', 'mdtraj.Topology', 'mdtraj.Trajectory', 'native.Native', 'nglview', 'openmm.Positions', 'openmm.Topology', 'parmed.Structure', 'yank.Topography']
parmed.Structure :  ['mdtraj', 'nglview']
mdanalysis.Universe :  ['mdtraj', 'nglview', 'pdb']
mdtraj.Topology :  ['openmm.Topology', 'parmed.Structure', 'yank.Topography']
openmm.Topology :  ['mdtraj.Topology', 'native', 'parmed.Structure', 'yank.Topography']
moldyn.Native :  ['

A second example:

In [26]:
system_parmed = molmodmt.load(MOL2_example_file,'parmed')

In [27]:
system_mdtraj = molmodmt.convert(system_parmed,'mdtraj')

In [28]:
molmodmt.convert(system_mdtraj,'caffeine.pdb')

In [29]:
os.listdir('.')

['examples_MolSys',
 'caffeine.pdb',
 '.ipynb_checkpoints',
 'examples_MolDyn',
 'Introduction.ipynb']

In [30]:
#less caffeine.pdb

In [31]:
os.remove('caffeine.pdb')

## Selection

In [32]:
system_mdtraj     = molmodmt.load(PDB_example_file,'mdtraj')
system_pdbfixer   = molmodmt.load(PDB_example_file,'pdbfixer')
system_mdanalysis = molmodmt.load(PDB_example_file,'mdanalysis')
system_parmed     = molmodmt.load(PDB_example_file,'parmed')

/home/diego/Myopt/Miniconda/miniconda3/envs/MolModMT_devel/lib/python3.6/site-packages/mdtraj/formats/pdb/pdbfile.py:196: UserWarning: Unlikely unit cell vectors detected in PDB file likely resulting from a dummy CRYST1 record. Discarding unit cell vectors.
  warnings.warn('Unlikely unit cell vectors detected in PDB file likely '


In [33]:
molmodmt.select(system_mdtraj,'name CA and resid 10 to 20')

array([177, 184, 198, 209, 220, 227, 251, 265, 279, 293])

In [34]:
molmodmt.select(system_pdbfixer,'name CA and resid 10 to 20')

array([177, 184, 198, 209, 220, 227, 251, 265, 279, 293])

In [35]:
molmodmt.select(system_mdanalysis,'name CA and resid 10 to 20')

/home/diego/Myopt/Miniconda/miniconda3/envs/MolModMT_devel/lib/python3.6/site-packages/mdtraj/utils/unitcell.py:78: UserWarning: All your angles were less than 2*pi. Did you accidentally give me radians?
  warnings.warn('All your angles were less than 2*pi. Did you accidentally give me radians?')
/home/diego/Myopt/Miniconda/miniconda3/envs/MolModMT_devel/lib/python3.6/site-packages/mdtraj/utils/unitcell.py:87: RuntimeWarning: invalid value encountered in true_divide
  cy = c_length*(np.cos(alpha) - np.cos(beta)*np.cos(gamma)) / np.sin(gamma)
/home/diego/Myopt/Miniconda/miniconda3/envs/MolModMT_devel/lib/python3.6/site-packages/mdtraj/utils/unitcell.py:99: RuntimeWarning: invalid value encountered in greater
  c[np.logical_and(c>-tol, c<tol)] = 0.0
/home/diego/Myopt/Miniconda/miniconda3/envs/MolModMT_devel/lib/python3.6/site-packages/mdtraj/utils/unitcell.py:99: RuntimeWarning: invalid value encountered in less
  c[np.logical_and(c>-tol, c<tol)] = 0.0
/home/diego/Myopt/Miniconda/minicon

array([177, 184, 198, 209, 220, 227, 251, 265, 279, 293])

In [36]:
molmodmt.select(system_parmed,'name CA and resid 10 to 20')

array([177, 184, 198, 209, 220, 227, 251, 265, 279, 293])

In [37]:
molmodmt.select(PDB_example_file,'name CA and resid 10 to 20')

array([177, 184, 198, 209, 220, 227, 251, 265, 279, 293])

In [38]:
molmodmt.select("pdb:1l2y",'name CA and resid 10 to 20')

array([177, 184, 198, 209, 220, 227, 251, 265, 279, 293])

In [39]:
molmodmt.select(system_mdanalysis,'name CA and (resid 10:20)','mdanalysis')

array([171, 178, 185, 199, 210, 221, 228, 252, 266, 280, 294])

In [40]:
molmodmt.select(system_parmed,':10-20@CA','parmed')

[170, 177, 184, 198, 209, 220, 227, 251, 265, 279, 293]

Geometric selection

## Extract part of a molecular system

## Viewing molecular systems

In [41]:
molmodmt.info_viewers()

In [42]:
molmodmt.info_viewers(for_form='pdb')

['nglview']

In [43]:
molmodmt.info_viewers(to_viewer='nglview')

['mdanalysis',
 'mdanalysis.Universe',
 'mdtraj.Trajectory',
 'modeller.Modeller',
 'mol2',
 'moldyn.Native',
 'molsys.Native',
 'openmm',
 'parmed.Structure',
 'pdb',
 'pdb:id',
 'pdbfixer.PDBFixer']

In [44]:
view=molmodmt.view(MOL2_example_file)
view

NGLWidget()

In [45]:
view=molmodmt.view('pdb:1l2y')
view

NGLWidget()

In [46]:
system_pdbfixer = molmodmt.load(PDB_example_file,'pdbfixer')
view=molmodmt.view(system_pdbfixer)
view

NGLWidget()