In [1]:
import molsysmt as msm
from molsysmt import pyunitwizard as puw
import numpy as np

import openmm as mm
from openmm import app
from openmm import unit

In [2]:
#import os
#from sys import stdout
#from mdtraj.reporters import HDF5Reporter
#from pathlib import Path
#import shutil

In [3]:
modeller = msm.convert(msm.systems['Trp-Cage']['1l2y.h5msm'], to_form='openmm.Modeller', structure_indices=0)
forcefield = app.ForceField("amber14-all.xml", "amber14/tip3p.xml")
system = forcefield.createSystem(modeller.topology, nonbondedMethod=app.NoCutoff, constraints=app.HBonds)
integrator = mm.LangevinIntegrator(300*unit.kelvin, 1.0/unit.picosecond, 2.0*unit.femtoseconds)
platform = mm.Platform.getPlatformByName('CPU')
simulation = app.Simulation(modeller.topology, system, integrator, platform)
simulation.context.setPositions(modeller.positions)
simulation.minimizeEnergy()
simulation.context.setVelocitiesToTemperature(300*unit.kelvin)

In [4]:
reporter = msm.thirds.openmm.reporters.StructuresDictReporter(100, time=True, coordinates=True, velocities=True,
             potentialEnergy=True, kineticEnergy=True, totalEnergy=True, temperature=True, box=True)

In [5]:
simulation.reporters.append(reporter)

In [6]:
simulation.step(1000)

In [7]:
traj_dict=reporter.finalize()

In [8]:
traj_dict

{'time': [0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ] ps,
 'coordinates': [[[-0.72188784  0.74636066  0.05813137]
   [-0.81043531  0.64553013 -0.00369961]
   [-0.73617225  0.5198318  -0.0486595 ]
   ...
   [-0.30431123  0.95345676  0.02049058]
   [-0.36000762  0.93144413  0.18751983]
   [-0.12497457  0.86743548  0.21938995]]
 
  [[-0.72297679  0.75950193  0.1033608 ]
   [-0.81054603  0.6797014   0.011069  ]
   [-0.75025977  0.54347444 -0.02469187]
   ...
   [-0.28984313  0.94931681  0.00860516]
   [-0.34914685  0.93085583  0.18166777]
   [-0.09713665  0.85020737  0.16878855]]
 
  [[-0.69809542  0.79990165  0.11378251]
   [-0.79235712  0.73827248  0.01545496]
   [-0.75864621  0.5912139  -0.01251315]
   ...
   [-0.3001207   0.95915799  0.04391413]
   [-0.33717406  0.91896417  0.21398136]
   [-0.10241378  0.84819644  0.18889462]]
 
  ...
 
  [[-0.62782934  0.85382559 -0.00604494]
   [-0.67765962  0.84164945 -0.14239682]
   [-0.69998651  0.69796684 -0.170781  ]
   ...
   [-0.22086467  0.9