In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import molsysmt as msm

# Get dihedral angles

## How to get any dihedral angle

Lets load a molecular systems to illustrate how MolSysMT works with the dihedral angles:

In [3]:
molecular_system = msm.convert(msm.demo['Met-enkephalin']['vacuum.msmpk'], to_form='molsysmt.MolSys')

In [4]:
msm.info(molecular_system)

In [5]:
view = msm.view(molecular_system)
view.clear()
view.add_ball_and_stick('all')
view

NGLWidget()

A dihedral angles is defined by three vectors $\vec{O_1E_1}$, $\vec{O_2E_2}$ y $\vec{O_3E_3}$, where $O_i$ and $E_i$ are the origin and end points of vector $i$. In molecular physics, a dihedral angle is a degree of freedom defined by three consecutive covalent bonds $\vec{O_1O_2}$, $\vec{O_2O_3}$, $\vec{O_3E_3}$ where in this context $O_1$, $O_2$, $O_3$ and $E_3$ are the position of the atoms defining the covalent chain. Thus, before showing how the dihedral angles are computed with `molsysmt.dihedral_angles`, lets have a look to the section 'How to get the covalent chains' where the methods `molsysmt.covalent_chains` and `molsysmt.covalent_dihedral_quartets` are introduced.

Lets first get all 4 atoms sequences in our molecular system covalently bound with the following names and order: C-N-CA-CB.

In [6]:
covalent_chains = msm.topology.get_covalent_chains(molecular_system, chain=['atom_name=="C"', 'atom_name=="N"',
                                                               'atom_name=="CA"', 'atom_name=="C"'])

In [7]:
covalent_chains

array([[19, 21, 23, 26],
       [26, 28, 30, 33],
       [33, 35, 37, 53],
       [53, 55, 57, 70]])

Lets have a look to the third C-N-CA-C atoms chain found in our molecular system: 

In [8]:
view = msm.view(molecular_system, viewer='NGLView')
view.clear()
selection_quartet = msm.select(molecular_system, selection=covalent_chains[2], to_syntax='NGLView')
view.add_ball_and_stick('all', color='white')
view.add_ball_and_stick(selection_quartet, color='orange')
view

NGLWidget()

The dihedral angle defined by the three consecutive vectors made by these atoms can be calculated as: 

In [9]:
dihedral_angles = msm.structure.get_dihedral_angles(molecular_system, quartets=covalent_chains[2])

In [10]:
dihedral_angles

array([[-179.99976415]]) <Unit('degree')>

The method `molsysmt.covalent_chains` needs as input argument the atom names defining the dihedral angle, but you probably don't remember how $\phi$ or $\psi$ are defined. To keep it simple, MolSysMT includes a specific method named `molsysmt.covalent_dihedral_quartets` that accepts dihedral angles names as input argument:

In [11]:
covalent_chains = msm.topology.get_covalent_dihedral_quartets(molecular_system, dihedral_angle='phi')

In [12]:
covalent_chains

array([[19, 21, 23, 26],
       [26, 28, 30, 33],
       [33, 35, 37, 53],
       [53, 55, 57, 70]])

The input argument 'quartets' accepts a list of atoms quartets to compute the corresponding dihedral angles:

In [13]:
dihedral_angles = msm.structure.get_dihedral_angles(molecular_system,
                                          quartets=covalent_chains)

In [14]:
dihedral_angles

array([[-179.9997655 , -179.99976355, -179.99976415, -179.99976565]]) <Unit('degree')>

The output object is a numpy array with shape: (n_frames, n_angles). As it can be checked in XXX, angles in MolSysMT are expressed in degrees.

In [15]:
dihedral_angles.shape

(1, 4)

Lets add another molecular system to see the result when multiple frames are present:

In [16]:
traj_file = msm.demo['pentalanine']['traj.h5']
molecular_system = msm.convert(traj_file, to_form='molsysmt.MolSys')
msm.info(molecular_system)

In [17]:
covalent_chains = msm.topology.get_covalent_dihedral_quartets(molecular_system, dihedral_angle="phi-psi",
                                                 selection='group_index==[3,4]')

In [18]:
covalent_chains.shape

(2, 4)

In [19]:
dihedral_angles = msm.structure.get_dihedral_angles(molecular_system, quartets=covalent_chains)

In [20]:
dihedral_angles.shape

(5000, 2)

We can also compute the dihedral angles for a specific set of frames:

In [22]:
dihedral_angles = msm.structure.get_dihedral_angles(molecular_system, quartets=covalent_chains,
                                          structure_indices=range(1000))

In [23]:
dihedral_angles.shape

(1000, 2)

Having the atoms quartets is very convenient if the method is going to be repeated multiple times. If, however, the method is going to be applied just once, the name of the dihedral angles can be introduced as the value of the input argument `dihedral_angle`:

In [24]:
phi_angles = msm.structure.get_dihedral_angles(molecular_system, dihedral_angle='phi')

In [25]:
phi_angles.shape

(5000, 5)

As well as the method `molsysmt.covalent_dihedral_quartets`, `molsysmt.get_dihedral_angles` accepts the value 'all' in its input argument `dihedral_angle`:

In [26]:
all_angles = msm.structure.get_dihedral_angles(molecular_system, dihedral_angle='all',
                                    selection='group_index==[1,2,3]')

In [27]:
all_angles.shape

(5000, 6)