In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import molsysmt as msm
import numpy as np
import matplotlib.pyplot as plt

# Get principal geometric axis

In [3]:
import molsysmt as msm
import numpy as np

In [4]:
coordinates = np.zeros([1,8,3]) * msm.pyunitwizard.unit('nm')

In [5]:
coordinates[0,0,:] = msm.pyunitwizard.quantity('[0,0,0] nm')
coordinates[0,1,:] = msm.pyunitwizard.quantity('[0,1,0] nm')
coordinates[0,2,:] = msm.pyunitwizard.quantity('[2,1,0] nm')
coordinates[0,3,:] = msm.pyunitwizard.quantity('[2,0,0] nm')

coordinates[0,4,:] = msm.pyunitwizard.quantity('[0,0,5] nm')
coordinates[0,5,:] = msm.pyunitwizard.quantity('[0,1,5] nm')
coordinates[0,6,:] = msm.pyunitwizard.quantity('[2,1,5] nm')
coordinates[0,7,:] = msm.pyunitwizard.quantity('[2,0,5] nm')

In [8]:
axis, variances = msm.structure.get_principal_geometric_axis(coordinates)

In [9]:
for ii in range(3):
    print(axis[0,ii,:], variances[0,ii])

[0. 1. 0.] 0.25
[1. 0. 0.] 1.0
[0. 0. 1.] 6.25
