In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import molsysmt as msm
import numpy as np

# Translate

In [3]:
molecular_system = msm.demo['Met-enkephalin']['vacuum.msmpk']
molecular_system = msm.convert(molecular_system)

In [4]:
msm.info(molecular_system)

In [5]:
msm.get(molecular_system, coordinates=True)

array([[[ 3.32577000e-01,  1.54790900e-01, -1.60000000e-07],
        [ 3.90940700e-01,  7.23611000e-02, -2.70000000e-07],
        [ 3.97004800e-01,  2.84579500e-01, -1.00000000e-08],
        [ 3.67166300e-01,  3.40012900e-01, -8.89820000e-02],
        [ 3.57696500e-01,  3.65383800e-01,  1.23214300e-01],
        [ 2.49699500e-01,  3.80107500e-01,  1.24137900e-01],
        [ 3.87748400e-01,  3.11579500e-01,  2.13119700e-01],
        [ 4.26732800e-01,  4.99626700e-01,  1.19494600e-01],
        [ 4.05992700e-01,  5.91891100e-01,  2.22728000e-01],
        [ 3.40010800e-01,  5.66821800e-01,  3.05787700e-01],
        [ 4.69999800e-01,  7.16354700e-01,  2.19279100e-01],
        [ 4.53852200e-01,  7.88189100e-01,  2.99653800e-01],
        [ 5.54747100e-01,  7.48554200e-01,  1.12597000e-01],
        [ 6.16925500e-01,  8.69461700e-01,  1.09246800e-01],
        [ 5.95632700e-01,  9.24698400e-01,  1.84821400e-01],
        [ 5.75487500e-01,  6.56290000e-01,  9.36350000e-03],
        [ 6.41469400e-01,  6.81359500e-01, -7.36962000e-02],
        [ 5.11480600e-01,  5.31826300e-01,  1.28119000e-02],
        [ 5.27628600e-01,  4.59992000e-01, -6.75627000e-02],
        [ 5.48554100e-01,  2.70520700e-01, -4.40000000e-07],
        [ 6.00882400e-01,  1.59317500e-01, -8.40000000e-07],
        [ 6.19100710e-01,  3.83858360e-01, -5.10000000e-07],
        [ 5.71528680e-01,  4.72953230e-01, -2.80000000e-07],
        [ 7.64000760e-01,  3.83858370e-01, -7.40000000e-07],
        [ 8.00385850e-01,  3.32483910e-01,  8.89811800e-02],
        [ 8.00385620e-01,  3.32484710e-01, -8.89832200e-02],
        [ 8.17053500e-01,  5.26512630e-01, -2.00000000e-07],
        [ 7.39543620e-01,  6.21888890e-01,  3.40000000e-07],
        [ 9.49772640e-01,  5.40930590e-01, -1.80000000e-07],
        [ 1.00942389e+00,  4.59427690e-01, -5.20000000e-07],
        [ 1.01260995e+00,  6.71496650e-01,  1.40000000e-07],
        [ 9.82096310e-01,  7.26561530e-01, -8.89817100e-02],
        [ 9.82097020e-01,  7.26560790e-01,  8.89826900e-02],
        [ 1.16415922e+00,  6.57437850e-01, -4.90000000e-07],
        [ 1.21648765e+00,  5.46234670e-01, -1.16000000e-06],
        [ 1.23470583e+00,  7.70775510e-01, -4.30000000e-07],
        [ 1.18713380e+00,  8.59870380e-01,  2.00000000e-08],
        [ 1.37960588e+00,  7.70775520e-01, -8.30000000e-07],
        [ 1.41599108e+00,  7.19400890e-01,  8.89809500e-02],
        [ 1.43450510e+00,  6.99638470e-01, -1.23215440e-01],
        [ 1.39967391e+00,  5.96357650e-01, -1.24139270e-01],
        [ 1.39967398e+00,  7.50479890e-01, -2.13120630e-01],
        [ 1.58515545e+00,  6.94503140e-01, -1.32110110e-01],
        [ 1.64674665e+00,  6.31641950e-01, -2.40990700e-01],
        [ 1.58595244e+00,  5.86406890e-01, -3.19341520e-01],
        [ 1.78642247e+00,  6.26880600e-01, -2.49237350e-01],
        [ 1.83437574e+00,  5.77938820e-01, -3.34008770e-01],
        [ 1.86450722e+00,  6.84980480e-01, -1.48603520e-01],
        [ 1.97325479e+00,  6.81273500e-01, -1.55024120e-01],
        [ 1.80291628e+00,  7.47841760e-01, -3.97227300e-02],
        [ 1.86371081e+00,  7.93076780e-01,  3.86278900e-02],
        [ 1.66324046e+00,  7.52603340e-01, -3.14757800e-02],
        [ 1.61528756e+00,  8.01545390e-01,  5.32956400e-02],
        [ 1.43439754e+00,  9.12770990e-01, -9.00000000e-08],
        [ 1.35805863e+00,  1.00908700e+00,  7.20000000e-07],
        [ 1.56728294e+00,  9.25566370e-01, -2.10000000e-07],
        [ 1.62593397e+00,  8.43340770e-01, -7.70000000e-07],
        [ 1.63171074e+00,  1.05535497e+00,  2.70000000e-07],
        [ 1.60187203e+00,  1.11078871e+00, -8.89814300e-02],
        [ 1.59240272e+00,  1.13615880e+00,  1.23214980e-01],
        [ 1.48440573e+00,  1.15088250e+00,  1.24138890e-01],
        [ 1.62245484e+00,  1.08235416e+00,  2.13120110e-01],
        [ 1.66212482e+00,  1.27173522e+00,  1.19458730e-01],
        [ 1.77013331e+00,  1.25709282e+00,  1.18579520e-01],
        [ 1.63208410e+00,  1.32562136e+00,  2.95985100e-02],
        [ 1.61643746e+00,  1.368901

In [6]:
n_atoms = msm.get(molecular_system, n_atoms=True)
shifts = np.ones([n_atoms,3], dtype=float)*msm.puw.unit('nm')

In [7]:
molecular_system = msm.structure.translate(molecular_system, translation=shifts)

In [8]:
coordinates = msm.get(molecular_system, coordinates=True)
coordinates

array([[[1.332577  , 1.1547909 , 0.99999984],
        [1.3909407 , 1.0723611 , 0.99999973],
        [1.3970048 , 1.2845795 , 0.99999999],
        [1.3671663 , 1.3400129 , 0.911018  ],
        [1.3576965 , 1.3653838 , 1.1232143 ],
        [1.2496995 , 1.3801075 , 1.1241379 ],
        [1.3877484 , 1.3115795 , 1.2131197 ],
        [1.4267328 , 1.4996267 , 1.1194946 ],
        [1.4059927 , 1.5918911 , 1.222728  ],
        [1.3400108 , 1.5668218 , 1.3057877 ],
        [1.4699998 , 1.7163547 , 1.2192791 ],
        [1.4538522 , 1.7881891 , 1.2996538 ],
        [1.5547471 , 1.7485542 , 1.112597  ],
        [1.6169255 , 1.8694617 , 1.1092468 ],
        [1.5956327 , 1.9246984 , 1.1848214 ],
        [1.5754875 , 1.65629   , 1.0093635 ],
        [1.6414694 , 1.6813595 , 0.9263038 ],
        [1.5114806 , 1.5318263 , 1.0128119 ],
        [1.5276286 , 1.459992  , 0.9324373 ],
        [1.5485541 , 1.2705207 , 0.99999956],
        [1.6008824 , 1.1593175 , 0.99999916],
        [1.61910071, 1.38385836, 0.99999949],
        [1.57152868, 1.47295323, 0.99999972],
        [1.76400076, 1.38385837, 0.99999926],
        [1.80038585, 1.33248391, 1.08898118],
        [1.80038562, 1.33248471, 0.91101678],
        [1.8170535 , 1.52651263, 0.9999998 ],
        [1.73954362, 1.62188889, 1.00000034],
        [1.94977264, 1.54093059, 0.99999982],
        [2.00942389, 1.45942769, 0.99999948],
        [2.01260995, 1.67149665, 1.00000014],
        [1.98209631, 1.72656153, 0.91101829],
        [1.98209702, 1.72656079, 1.08898269],
        [2.16415922, 1.65743785, 0.99999951],
        [2.21648765, 1.54623467, 0.99999884],
        [2.23470583, 1.77077551, 0.99999957],
        [2.1871338 , 1.85987038, 1.00000002],
        [2.37960588, 1.77077552, 0.99999917],
        [2.41599108, 1.71940089, 1.08898095],
        [2.4345051 , 1.69963847, 0.87678456],
        [2.39967391, 1.59635765, 0.87586073],
        [2.39967398, 1.75047989, 0.78687937],
        [2.58515545, 1.69450314, 0.86788989],
        [2.64674665, 1.63164195, 0.7590093 ],
        [2.58595244, 1.58640689, 0.68065848],
        [2.78642247, 1.6268806 , 0.75076265],
        [2.83437574, 1.57793882, 0.66599123],
        [2.86450722, 1.68498048, 0.85139648],
        [2.97325479, 1.6812735 , 0.84497588],
        [2.80291628, 1.74784176, 0.96027727],
        [2.86371081, 1.79307678, 1.03862789],
        [2.66324046, 1.75260334, 0.96852422],
        [2.61528756, 1.80154539, 1.05329564],
        [2.43439754, 1.91277099, 0.99999991],
        [2.35805863, 2.009087  , 1.00000072],
        [2.56728294, 1.92556637, 0.99999979],
        [2.62593397, 1.84334077, 0.99999923],
        [2.63171074, 2.05535497, 1.00000027],
        [2.60187203, 2.11078871, 0.91101857],
        [2.59240272, 2.1361588 , 1.12321498],
        [2.48440573, 2.1508825 , 1.12413889],
        [2.62245484, 2.08235416, 1.21312011],
        [2.66212482, 2.27173522, 1.11945873],
        [2.77013331, 2.25709282, 1.11857952],
        [2.6320841 , 2.32562136, 1.02959851],
        [2.61643746, 2.36890107, 1.26517231],
        [2.71002768, 2.51708739, 1.23409675],
        [2.67806446, 2.56117934, 1.13967619],
        [2.69329737, 2.58830418, 1.31490066],
        [2.81611387, 2.49265091, 1.22865691],
        [2.78326004, 2.04129617, 0.99999944],
        [2.83558834, 1.93009297, 0.99999849]]]) <Unit('nanometer')>

In [9]:
shifts = np.array([-1.0, -1.0, -1.0], dtype=float)*msm.puw.unit('nm')
molecular_system = msm.structure.translate(molecular_system, translation=shifts,
                                           selection=[0,1,2], in_place=False)

In [10]:
msm.get(molecular_system, coordinates=True)

array([[[ 3.32577000e-01,  1.54790900e-01, -1.60000000e-07],
        [ 3.90940700e-01,  7.23611000e-02, -2.70000000e-07],
        [ 3.97004800e-01,  2.84579500e-01, -1.00000001e-08],
        [ 1.36716630e+00,  1.34001290e+00,  9.11018000e-01],
        [ 1.35769650e+00,  1.36538380e+00,  1.12321430e+00],
        [ 1.24969950e+00,  1.38010750e+00,  1.12413790e+00],
        [ 1.38774840e+00,  1.31157950e+00,  1.21311970e+00],
        [ 1.42673280e+00,  1.49962670e+00,  1.11949460e+00],
        [ 1.40599270e+00,  1.59189110e+00,  1.22272800e+00],
        [ 1.34001080e+00,  1.56682180e+00,  1.30578770e+00],
        [ 1.46999980e+00,  1.71635470e+00,  1.21927910e+00],
        [ 1.45385220e+00,  1.78818910e+00,  1.29965380e+00],
        [ 1.55474710e+00,  1.74855420e+00,  1.11259700e+00],
        [ 1.61692550e+00,  1.86946170e+00,  1.10924680e+00],
        [ 1.59563270e+00,  1.92469840e+00,  1.18482140e+00],
        [ 1.57548750e+00,  1.65629000e+00,  1.00936350e+00],
        [ 1.64146940e+00,  1.68135950e+00,  9.26303800e-01],
        [ 1.51148060e+00,  1.53182630e+00,  1.01281190e+00],
        [ 1.52762860e+00,  1.45999200e+00,  9.32437300e-01],
        [ 1.54855410e+00,  1.27052070e+00,  9.99999560e-01],
        [ 1.60088240e+00,  1.15931750e+00,  9.99999160e-01],
        [ 1.61910071e+00,  1.38385836e+00,  9.99999490e-01],
        [ 1.57152868e+00,  1.47295323e+00,  9.99999720e-01],
        [ 1.76400076e+00,  1.38385837e+00,  9.99999260e-01],
        [ 1.80038585e+00,  1.33248391e+00,  1.08898118e+00],
        [ 1.80038562e+00,  1.33248471e+00,  9.11016780e-01],
        [ 1.81705350e+00,  1.52651263e+00,  9.99999800e-01],
        [ 1.73954362e+00,  1.62188889e+00,  1.00000034e+00],
        [ 1.94977264e+00,  1.54093059e+00,  9.99999820e-01],
        [ 2.00942389e+00,  1.45942769e+00,  9.99999480e-01],
        [ 2.01260995e+00,  1.67149665e+00,  1.00000014e+00],
        [ 1.98209631e+00,  1.72656153e+00,  9.11018290e-01],
        [ 1.98209702e+00,  1.72656079e+00,  1.08898269e+00],
        [ 2.16415922e+00,  1.65743785e+00,  9.99999510e-01],
        [ 2.21648765e+00,  1.54623467e+00,  9.99998840e-01],
        [ 2.23470583e+00,  1.77077551e+00,  9.99999570e-01],
        [ 2.18713380e+00,  1.85987038e+00,  1.00000002e+00],
        [ 2.37960588e+00,  1.77077552e+00,  9.99999170e-01],
        [ 2.41599108e+00,  1.71940089e+00,  1.08898095e+00],
        [ 2.43450510e+00,  1.69963847e+00,  8.76784560e-01],
        [ 2.39967391e+00,  1.59635765e+00,  8.75860730e-01],
        [ 2.39967398e+00,  1.75047989e+00,  7.86879370e-01],
        [ 2.58515545e+00,  1.69450314e+00,  8.67889890e-01],
        [ 2.64674665e+00,  1.63164195e+00,  7.59009300e-01],
        [ 2.58595244e+00,  1.58640689e+00,  6.80658480e-01],
        [ 2.78642247e+00,  1.62688060e+00,  7.50762650e-01],
        [ 2.83437574e+00,  1.57793882e+00,  6.65991230e-01],
        [ 2.86450722e+00,  1.68498048e+00,  8.51396480e-01],
        [ 2.97325479e+00,  1.68127350e+00,  8.44975880e-01],
        [ 2.80291628e+00,  1.74784176e+00,  9.60277270e-01],
        [ 2.86371081e+00,  1.79307678e+00,  1.03862789e+00],
        [ 2.66324046e+00,  1.75260334e+00,  9.68524220e-01],
        [ 2.61528756e+00,  1.80154539e+00,  1.05329564e+00],
        [ 2.43439754e+00,  1.91277099e+00,  9.99999910e-01],
        [ 2.35805863e+00,  2.00908700e+00,  1.00000072e+00],
        [ 2.56728294e+00,  1.92556637e+00,  9.99999790e-01],
        [ 2.62593397e+00,  1.84334077e+00,  9.99999230e-01],
        [ 2.63171074e+00,  2.05535497e+00,  1.00000027e+00],
        [ 2.60187203e+00,  2.11078871e+00,  9.11018570e-01],
        [ 2.59240272e+00,  2.13615880e+00,  1.12321498e+00],
        [ 2.48440573e+00,  2.15088250e+00,  1.12413889e+00],
        [ 2.62245484e+00,  2.08235416e+00,  1.21312011e+00],
        [ 2.66212482e+00,  2.27173522e+00,  1.11945873e+00],
        [ 2.77013331e+00,  2.25709282e+00,  1.11857952e+00],
        [ 2.63208410e+00,  2.32562136e+00,  1.02959851e+00],
        [ 2.61643746e+00,  2.368901