In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import molsysmt as msm
import numpy as np

# Translate

In [3]:
molecular_system = msm.systems['Met-enkephalin']['met_enkephalin.h5msm']
molecular_system = msm.convert(molecular_system)

In [4]:
msm.info(molecular_system)

In [5]:
msm.get(molecular_system, coordinates=True)

array([[[ 3.32576990e-01,  1.54790893e-01, -1.59999999e-07],
        [ 3.90940696e-01,  7.23610967e-02, -2.69999987e-07],
        [ 3.97004813e-01,  2.84579486e-01, -9.99999994e-09],
        [ 3.67166311e-01,  3.40012908e-01, -8.89820009e-02],
        [ 3.57696503e-01,  3.65383804e-01,  1.23214297e-01],
        [ 2.49699503e-01,  3.80107492e-01,  1.24137901e-01],
        [ 3.87748390e-01,  3.11579496e-01,  2.13119701e-01],
        [ 4.26732808e-01,  4.99626696e-01,  1.19494602e-01],
        [ 4.05992687e-01,  5.91891110e-01,  2.22727999e-01],
        [ 3.40010792e-01,  5.66821814e-01,  3.05787712e-01],
        [ 4.69999790e-01,  7.16354728e-01,  2.19279096e-01],
        [ 4.53852206e-01,  7.88189113e-01,  2.99653798e-01],
        [ 5.54747105e-01,  7.48554230e-01,  1.12597004e-01],
        [ 6.16925478e-01,  8.69461715e-01,  1.09246798e-01],
        [ 5.95632672e-01,  9.24698412e-01,  1.84821397e-01],
        [ 5.75487494e-01,  6.56289995e-01,  9.36350040e-03],
        [ 6.41469419e-01,  6.81359529e-01, -7.36962035e-02],
        [ 5.11480629e-01,  5.31826317e-01,  1.28119001e-02],
        [ 5.27628601e-01,  4.59991992e-01, -6.75626993e-02],
        [ 5.48554122e-01,  2.70520687e-01, -4.40000008e-07],
        [ 6.00882411e-01,  1.59317493e-01, -8.39999984e-07],
        [ 6.19100690e-01,  3.83858353e-01, -5.10000007e-07],
        [ 5.71528673e-01,  4.72953230e-01, -2.79999995e-07],
        [ 7.64000773e-01,  3.83858383e-01, -7.40000019e-07],
        [ 8.00385833e-01,  3.32483917e-01,  8.89811814e-02],
        [ 8.00385594e-01,  3.32484722e-01, -8.89832228e-02],
        [ 8.17053497e-01,  5.26512623e-01, -2.00000002e-07],
        [ 7.39543617e-01,  6.21888876e-01,  3.40000014e-07],
        [ 9.49772656e-01,  5.40930569e-01, -1.80000001e-07],
        [ 1.00942385e+00,  4.59427685e-01, -5.20000015e-07],
        [ 1.01260996e+00,  6.71496630e-01,  1.39999997e-07],
        [ 9.82096314e-01,  7.26561546e-01, -8.89817104e-02],
        [ 9.82097030e-01,  7.26560771e-01,  8.89826864e-02],
        [ 1.16415918e+00,  6.57437861e-01, -4.89999991e-07],
        [ 1.21648765e+00,  5.46234667e-01, -1.16000001e-06],
        [ 1.23470581e+00,  7.70775497e-01, -4.30000000e-07],
        [ 1.18713379e+00,  8.59870374e-01,  1.99999999e-08],
        [ 1.37960589e+00,  7.70775497e-01, -8.29999976e-07],
        [ 1.41599107e+00,  7.19400883e-01,  8.89809504e-02],
        [ 1.43450511e+00,  6.99638486e-01, -1.23215437e-01],
        [ 1.39967394e+00,  5.96357644e-01, -1.24139272e-01],
        [ 1.39967394e+00,  7.50479877e-01, -2.13120624e-01],
        [ 1.58515549e+00,  6.94503129e-01, -1.32110104e-01],
        [ 1.64674664e+00,  6.31641924e-01, -2.40990698e-01],
        [ 1.58595240e+00,  5.86406887e-01, -3.19341511e-01],
        [ 1.78642249e+00,  6.26880586e-01, -2.49237344e-01],
        [ 1.83437574e+00,  5.77938795e-01, -3.34008783e-01],
        [ 1.86450720e+00,  6.84980452e-01, -1.48603514e-01],
        [ 1.97325480e+00,  6.81273520e-01, -1.55024126e-01],
        [ 1.80291629e+00,  7.47841775e-01, -3.97227295e-02],
        [ 1.86371076e+00,  7.93076754e-01,  3.86278890e-02],
        [ 1.66324043e+00,  7.52603352e-01, -3.14757787e-02],
        [ 1.61528754e+00,  8.01545382e-01,  5.32956384e-02],
        [ 1.43439758e+00,  9.12770987e-01, -9.00000003e-08],
        [ 1.35805857e+00,  1.00908697e+00,  7.20000003e-07],
        [ 1.56728292e+00,  9.25566375e-01, -2.09999996e-07],
        [ 1.62593400e+00,  8.43340755e-01, -7.69999986e-07],
        [ 1.63171077e+00,  1.05535495e+00,  2.69999987e-07],
        [ 1.60187209e+00,  1.11078870e+00, -8.89814273e-02],
        [ 1.59240270e+00,  1.13615882e+00,  1.23214982e-01],
        [ 1.48440576e+00,  1.15088248e+00,  1.24138892e-01],
        [ 1.62245488e+00,  1.08235419e+00,  2.13120103e-01],
        [ 1.66212487e+00,  1.27173519e+00,  1.19458728e-01],
        [ 1.77013326e+00,  1.25709283e+00,  1.18579522e-01],
        [ 1.63208413e+00,  1.32562137e+00,  2.95985099e-02],
        [ 1.61643744e+00,  1.368901

In [7]:
n_atoms = msm.get(molecular_system, n_atoms=True)
shifts = np.ones([n_atoms,3], dtype=float)*msm.pyunitwizard.unit('nm')

In [8]:
molecular_system = msm.structure.translate(molecular_system, translation=shifts)

In [9]:
coordinates = msm.get(molecular_system, coordinates=True)
coordinates

array([[[1.33257699, 1.15479089, 0.99999984],
        [1.3909407 , 1.0723611 , 0.99999973],
        [1.39700481, 1.28457949, 0.99999999],
        [1.36716631, 1.34001291, 0.911018  ],
        [1.3576965 , 1.3653838 , 1.1232143 ],
        [1.2496995 , 1.38010749, 1.1241379 ],
        [1.38774839, 1.3115795 , 1.2131197 ],
        [1.42673281, 1.4996267 , 1.1194946 ],
        [1.40599269, 1.59189111, 1.222728  ],
        [1.34001079, 1.56682181, 1.30578771],
        [1.46999979, 1.71635473, 1.2192791 ],
        [1.45385221, 1.78818911, 1.2996538 ],
        [1.5547471 , 1.74855423, 1.112597  ],
        [1.61692548, 1.86946172, 1.1092468 ],
        [1.59563267, 1.92469841, 1.1848214 ],
        [1.57548749, 1.65628999, 1.0093635 ],
        [1.64146942, 1.68135953, 0.9263038 ],
        [1.51148063, 1.53182632, 1.0128119 ],
        [1.5276286 , 1.45999199, 0.9324373 ],
        [1.54855412, 1.27052069, 0.99999956],
        [1.60088241, 1.15931749, 0.99999916],
        [1.61910069, 1.38385835, 0.99999949],
        [1.57152867, 1.47295323, 0.99999972],
        [1.76400077, 1.38385838, 0.99999926],
        [1.80038583, 1.33248392, 1.08898118],
        [1.80038559, 1.33248472, 0.91101678],
        [1.8170535 , 1.52651262, 0.9999998 ],
        [1.73954362, 1.62188888, 1.00000034],
        [1.94977266, 1.54093057, 0.99999982],
        [2.00942385, 1.45942768, 0.99999948],
        [2.01260996, 1.67149663, 1.00000014],
        [1.98209631, 1.72656155, 0.91101829],
        [1.98209703, 1.72656077, 1.08898269],
        [2.16415918, 1.65743786, 0.99999951],
        [2.21648765, 1.54623467, 0.99999884],
        [2.23470581, 1.7707755 , 0.99999957],
        [2.18713379, 1.85987037, 1.00000002],
        [2.37960589, 1.7707755 , 0.99999917],
        [2.41599107, 1.71940088, 1.08898095],
        [2.43450511, 1.69963849, 0.87678456],
        [2.39967394, 1.59635764, 0.87586073],
        [2.39967394, 1.75047988, 0.78687938],
        [2.58515549, 1.69450313, 0.8678899 ],
        [2.64674664, 1.63164192, 0.7590093 ],
        [2.5859524 , 1.58640689, 0.68065849],
        [2.78642249, 1.62688059, 0.75076266],
        [2.83437574, 1.5779388 , 0.66599122],
        [2.8645072 , 1.68498045, 0.85139649],
        [2.9732548 , 1.68127352, 0.84497587],
        [2.80291629, 1.74784178, 0.96027727],
        [2.86371076, 1.79307675, 1.03862789],
        [2.66324043, 1.75260335, 0.96852422],
        [2.61528754, 1.80154538, 1.05329564],
        [2.43439758, 1.91277099, 0.99999991],
        [2.35805857, 2.00908697, 1.00000072],
        [2.56728292, 1.92556638, 0.99999979],
        [2.625934  , 1.84334075, 0.99999923],
        [2.63171077, 2.05535495, 1.00000027],
        [2.60187209, 2.1107887 , 0.91101857],
        [2.5924027 , 2.13615882, 1.12321498],
        [2.48440576, 2.15088248, 1.12413889],
        [2.62245488, 2.08235419, 1.2131201 ],
        [2.66212487, 2.27173519, 1.11945873],
        [2.77013326, 2.25709283, 1.11857952],
        [2.63208413, 2.32562137, 1.02959851],
        [2.61643744, 2.36890101, 1.2651723 ],
        [2.71002769, 2.51708734, 1.23409675],
        [2.67806447, 2.5611794 , 1.13967618],
        [2.69329739, 2.58830416, 1.31490067],
        [2.81611383, 2.49265087, 1.2286569 ],
        [2.78325999, 2.04129612, 0.99999944],
        [2.83558834, 1.93009299, 0.99999849]]]) <Unit('nanometer')>

In [10]:
shifts = np.array([-1.0, -1.0, -1.0], dtype=float)*msm.pyunitwizard.unit('nm')
molecular_system = msm.structure.translate(molecular_system, translation=shifts,
                                           selection=[0,1,2], in_place=False)

In [11]:
msm.get(molecular_system, coordinates=True)

array([[[ 3.32576990e-01,  1.54790893e-01, -1.59999999e-07],
        [ 3.90940696e-01,  7.23610967e-02, -2.69999987e-07],
        [ 3.97004813e-01,  2.84579486e-01, -9.99999994e-09],
        [ 1.36716631e+00,  1.34001291e+00,  9.11017999e-01],
        [ 1.35769650e+00,  1.36538380e+00,  1.12321430e+00],
        [ 1.24969950e+00,  1.38010749e+00,  1.12413790e+00],
        [ 1.38774839e+00,  1.31157950e+00,  1.21311970e+00],
        [ 1.42673281e+00,  1.49962670e+00,  1.11949460e+00],
        [ 1.40599269e+00,  1.59189111e+00,  1.22272800e+00],
        [ 1.34001079e+00,  1.56682181e+00,  1.30578771e+00],
        [ 1.46999979e+00,  1.71635473e+00,  1.21927910e+00],
        [ 1.45385221e+00,  1.78818911e+00,  1.29965380e+00],
        [ 1.55474710e+00,  1.74855423e+00,  1.11259700e+00],
        [ 1.61692548e+00,  1.86946172e+00,  1.10924680e+00],
        [ 1.59563267e+00,  1.92469841e+00,  1.18482140e+00],
        [ 1.57548749e+00,  1.65628999e+00,  1.00936350e+00],
        [ 1.64146942e+00,  1.68135953e+00,  9.26303796e-01],
        [ 1.51148063e+00,  1.53182632e+00,  1.01281190e+00],
        [ 1.52762860e+00,  1.45999199e+00,  9.32437301e-01],
        [ 1.54855412e+00,  1.27052069e+00,  9.99999560e-01],
        [ 1.60088241e+00,  1.15931749e+00,  9.99999160e-01],
        [ 1.61910069e+00,  1.38385835e+00,  9.99999490e-01],
        [ 1.57152867e+00,  1.47295323e+00,  9.99999720e-01],
        [ 1.76400077e+00,  1.38385838e+00,  9.99999260e-01],
        [ 1.80038583e+00,  1.33248392e+00,  1.08898118e+00],
        [ 1.80038559e+00,  1.33248472e+00,  9.11016777e-01],
        [ 1.81705350e+00,  1.52651262e+00,  9.99999800e-01],
        [ 1.73954362e+00,  1.62188888e+00,  1.00000034e+00],
        [ 1.94977266e+00,  1.54093057e+00,  9.99999820e-01],
        [ 2.00942385e+00,  1.45942768e+00,  9.99999480e-01],
        [ 2.01260996e+00,  1.67149663e+00,  1.00000014e+00],
        [ 1.98209631e+00,  1.72656155e+00,  9.11018290e-01],
        [ 1.98209703e+00,  1.72656077e+00,  1.08898269e+00],
        [ 2.16415918e+00,  1.65743786e+00,  9.99999510e-01],
        [ 2.21648765e+00,  1.54623467e+00,  9.99998840e-01],
        [ 2.23470581e+00,  1.77077550e+00,  9.99999570e-01],
        [ 2.18713379e+00,  1.85987037e+00,  1.00000002e+00],
        [ 2.37960589e+00,  1.77077550e+00,  9.99999170e-01],
        [ 2.41599107e+00,  1.71940088e+00,  1.08898095e+00],
        [ 2.43450511e+00,  1.69963849e+00,  8.76784563e-01],
        [ 2.39967394e+00,  1.59635764e+00,  8.75860728e-01],
        [ 2.39967394e+00,  1.75047988e+00,  7.86879376e-01],
        [ 2.58515549e+00,  1.69450313e+00,  8.67889896e-01],
        [ 2.64674664e+00,  1.63164192e+00,  7.59009302e-01],
        [ 2.58595240e+00,  1.58640689e+00,  6.80658489e-01],
        [ 2.78642249e+00,  1.62688059e+00,  7.50762656e-01],
        [ 2.83437574e+00,  1.57793880e+00,  6.65991217e-01],
        [ 2.86450720e+00,  1.68498045e+00,  8.51396486e-01],
        [ 2.97325480e+00,  1.68127352e+00,  8.44975874e-01],
        [ 2.80291629e+00,  1.74784178e+00,  9.60277271e-01],
        [ 2.86371076e+00,  1.79307675e+00,  1.03862789e+00],
        [ 2.66324043e+00,  1.75260335e+00,  9.68524221e-01],
        [ 2.61528754e+00,  1.80154538e+00,  1.05329564e+00],
        [ 2.43439758e+00,  1.91277099e+00,  9.99999910e-01],
        [ 2.35805857e+00,  2.00908697e+00,  1.00000072e+00],
        [ 2.56728292e+00,  1.92556638e+00,  9.99999790e-01],
        [ 2.62593400e+00,  1.84334075e+00,  9.99999230e-01],
        [ 2.63171077e+00,  2.05535495e+00,  1.00000027e+00],
        [ 2.60187209e+00,  2.11078870e+00,  9.11018573e-01],
        [ 2.59240270e+00,  2.13615882e+00,  1.12321498e+00],
        [ 2.48440576e+00,  2.15088248e+00,  1.12413889e+00],
        [ 2.62245488e+00,  2.08235419e+00,  1.21312010e+00],
        [ 2.66212487e+00,  2.27173519e+00,  1.11945873e+00],
        [ 2.77013326e+00,  2.25709283e+00,  1.11857952e+00],
        [ 2.63208413e+00,  2.32562137e+00,  1.02959851e+00],
        [ 2.61643744e+00,  2.368901